import {t} from './i18n';
import React,{useEffect,useState} from 'react';
import {api,viewKey} from './api';
import {Brand} from './icons';
import {LanguagePicker} from './language';
import {LanguagePack} from './i18n';
export type AgreementState={version:string;accepted:boolean};
export function AgreementGate({agreement,refresh,onClose,onRevoked,initialDeclined,language}:{agreement:AgreementState;language:{value:string;packs:LanguagePack[]};refresh:()=>Promise<void>;onClose?:()=>void;onRevoked?:(closed:boolean)=>void;initialDeclined?:boolean}){
 const[terms,setTerms]=useState(false),[privacy,setPrivacy]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[declined,setDeclined]=useState(initialDeclined??false),[confirmRevoke,setConfirmRevoke]=useState(false);
 useEffect(()=>{if(initialDeclined)setDeclined(true);},[initialDeclined]);
 async function accept(){setBusy(true);setError('');try{await api('agreement.accept',{version:agreement.version,userAgreement:terms,privacyStatement:privacy});await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function revoke(){setBusy(true);setError('');try{await api('agreement.revoke',{version:agreement.version,approve:true});const result=await api('agreement.decline',{view:viewKey()});onRevoked?.(result.closed);await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function decline(){if(agreement.accepted){setConfirmRevoke(true);return;}setBusy(true);setError('');try{const result=await api('agreement.decline',{view:viewKey()});if(!result.closed)setDeclined(true);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}

 async function selectLanguage(value:string){setBusy(true);setError('');try{await api('language.save',{language:value});await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const header=<header className="shell-header"><strong className="brand-title"><Brand wordmark/></strong><LanguagePicker value={language.value} packs={language.packs} disabled={busy} onChange={value=>void selectLanguage(value)}/></header>;

 if(declined)return <div className="app agreement-app">{header}<main className="empty-state"><h1>{t("请先阅读并同意使用协议")}</h1><button onClick={()=>{setTerms(false);setPrivacy(false);setDeclined(false);}}>{t("查看使用协议")}</button></main></div>;
 return <div className="app agreement-app">{header}<main className="agreement-body"><h1>{t("使用 Framely 前")}</h1><div className="agreement-documents"><section><h2>{t("用户协议")}</h2><p>{t("Framely 提供插件的集中安装、管理、运行和更新等功能。第三方插件由各自开发者提供，插件的功能、内容及运行行为由插件开发者负责。")}</p><p><strong>{t("Framely 不保证第三方插件的安全性、可靠性或兼容性。插件库收录、下载校验或权限提示不代表对插件安全性的认可或担保。")}</strong></p><p>{t("请自行甄别插件来源、安全性及所需权限，谨慎决定是否安装、授权或运行，并备份重要数据。插件可能读取或修改数据、访问网络、调整设备设置；授予较高权限可能影响系统和设备。")}</p><p><strong>{t("在适用法律允许的范围内，因第三方插件的安装、授权、运行、更新或卸载造成的数据丢失、隐私泄露、设备故障或其他损失，Framely 及其开发者不承担责任。")}</strong>{' '}{t("本协议不排除或限制法律规定不得免除或限制的责任及用户权利。")}</p><p>{t("不同意本协议时，请停止使用 Framely。协议发生变更时，需要重新确认。")}</p></section><section><h2>{t("隐私声明")}</h2><p>{t("Framely 本身不会主动收集、上传或出售用户个人信息，不内置用户行为跟踪或遥测上报。")}</p><p>{t("为提供管理功能，Framely 会在设备本地保存插件清单、配置、运行日志、协议同意记录及其他必要状态。访问密码仅保存加盐哈希值。")}</p><p>{t("获取插件目录、刷新订阅、下载插件和检查更新时，Framely 会按配置访问相应服务器；使用代理时，请求会经过相应代理服务。这些服务可能获知 IP 地址及请求信息，其数据处理由各自运营者负责。")}</p><p><strong>{t("第三方插件可能自行收集、读取或上传用户信息。Framely 不保证插件不会收集信息，也不保证插件的数据处理行为符合你的隐私期望。")}</strong>{' '}{t("请查看插件的权限、说明及隐私政策，自行决定是否使用。")}</p></section></div>{error&&<p className="error" role="alert">{error}</p>}</main><footer className="agreement-footer">{confirmRevoke?<div className="agreement-revoke" role="alert"><strong>{t("拒绝协议将停用全部插件")}</strong><p>{t("插件窗口将关闭。重新同意后，需自行启用插件。")}</p><div className="agreement-actions"><button disabled={busy} onClick={()=>setConfirmRevoke(false)}>{t("取消")}</button><button className="danger" disabled={busy} onClick={()=>void revoke()}>{busy?t("正在停用…"):t("确认拒绝并停用全部插件")}</button></div></div>:agreement.accepted?<><span>{t("用户协议与隐私声明")}</span><div className="agreement-actions"><button disabled={busy} onClick={onClose}>{t("返回关于")}</button><button disabled={busy} onClick={()=>void decline()}>{t("拒绝协议")}</button></div></>:<><div><label><input type="checkbox" checked={terms} onChange={e=>setTerms(e.target.checked)}/>{t("我已阅读并同意《用户协议》")}</label><label><input type="checkbox" checked={privacy} onChange={e=>setPrivacy(e.target.checked)}/>{t("我已阅读并同意《隐私声明》")}</label></div><div className="agreement-actions"><button disabled={busy} onClick={()=>void decline()}>{t("不同意并退出")}</button><button className="primary" disabled={!terms||!privacy||busy} onClick={()=>void accept()}>{busy?t("保存中…"):t("同意并继续")}</button></div></>}</footer></div>;
}
