import React,{useEffect,useRef,useState} from 'react';
import {IconPlayerPlay,IconPlayerStop,IconExternalLink,IconCopy,IconCheck,IconDeviceVisionPro,IconDeviceDesktop,IconCrop,IconEye,IconDeviceTv,IconRefresh,IconCast,IconMusic,IconVideo,IconWifi,IconArrowRight} from '@tabler/icons-react';
import {NetworkSettings,type NetworkPanel} from './network';
import {api} from './api';
import {SwitchRow} from './switch';
import {t} from './i18n';
import {CastVideo} from './cast-viewer';
import {FramingEditor} from './cast-framing-editor';
import {framePresets,frameRatios,type ReferenceView} from './cast-framing';
import './casting.css';

export type CastSettings={source:'screen'|'steamVR';output:'eye'|'raw';eye:'steamVR'|'left'|'right';width:number;height:number;fps:number;bitrateMbps:number;horizontalFov:number|null;centerX:number;centerY:number;systemAudio:boolean;microphone:boolean;airplay:boolean;dlna:boolean;receiverName:string};
type CastSession={id:string;protocol:string;accepted:boolean;width?:number;height?:number};
type Device={id:string;name:string};
type Runtime={running:boolean;error:string|null;dominantEye:number|null;watchPath:string|null;elapsedSeconds:number|null;preview?:boolean;view?:ReferenceView|null;receiverError?:string|null;sessions?:CastSession[];watchAddresses?:string[]};
export type CastPage='casting'|'casting-picture'|'casting-receive'|'casting-devices';
const titles:Record<CastPage,[string,string]>={casting:['网页观看','把头显画面分享给同一网络中的手机或电脑。'],'casting-picture':['画面与声音','选择画面来源，直接调整取景和输出画质。'],'casting-receive':['接收投屏','接收其他设备的音频和视频，在头显中打开。'],'casting-devices':['投到设备','选择同一网络中的设备，播放当前头显画面。']};
function Choices<T extends string|number>({label,value,options,onChange,disabled=false}:{label:string;value:T;options:{value:T;label:string;description?:string}[];onChange:(value:T)=>void;disabled?:boolean}){
 return <div className="cast-choice-group" role="radiogroup" aria-label={label}>{options.map((option,i)=><button type="button" role="radio" aria-checked={value===option.value} className={value===option.value?'selected':''} disabled={disabled} key={option.value} onClick={()=>onChange(option.value)} onKeyDown={e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const next=(i+(['ArrowLeft','ArrowUp'].includes(e.key)?-1:1)+options.length)%options.length;onChange(options[next].value);(e.currentTarget.parentElement?.children[next] as HTMLElement)?.focus();}}}><span>{option.label}</span>{option.description&&<small>{option.description}</small>}</button>)}</div>;
}
export function Casting({config,refresh,network,page='casting'}:{config:CastSettings;refresh:()=>Promise<void>;network:NetworkPanel;page?:CastPage}){
 const [draft,setDraft]=useState(config),[runtime,setRuntime]=useState<Runtime|null>(null),[pending,setPending]=useState(''),[error,setError]=useState(''),[saved,setSaved]=useState(false),[epoch,setEpoch]=useState(0),[devices,setDevices]=useState<Device[]>([]),[sending,setSending]=useState<string>(''),[copied,setCopied]=useState(false),[editing,setEditing]=useState(false),[searched,setSearched]=useState(false);
 const beforeFraming=useRef<Pick<CastSettings,'horizontalFov'|'centerX'|'centerY'>|null>(null),editorActive=useRef(false),deviceScan=useRef(0),alive=useRef(true);
 const captureSettings=({airplay,dlna,receiverName,...capture}:CastSettings)=>capture;
 const captureDirty=JSON.stringify(captureSettings(draft))!==JSON.stringify(captureSettings(config)),dirty=JSON.stringify(draft)!==JSON.stringify(config),busy=!!pending,screen=draft.source==='screen',eye=screen&&draft.output==='eye';
 const aspect=screen&&draft.output==='raw'?2:draft.width/draft.height;
 const ratio=frameRatios.find(r=>Math.abs(r.value-aspect)<.004)?.label;
 useEffect(()=>{setDraft(config);},[JSON.stringify(config)]);
 useEffect(()=>{alive.current=true;const poll=()=>void api<Runtime>('cast.status').then(v=>{if(alive.current)setRuntime(v);}).catch(e=>{if(alive.current)setError(e.message);});poll();const timer=setInterval(poll,2000);return()=>{alive.current=false;deviceScan.current++;clearInterval(timer);if(editorActive.current)void api('cast.preview.end').catch(()=>{});};},[]);
 function change(patch:Partial<CastSettings>){setDraft(v=>({...v,...patch}));setSaved(false);}
 async function action(name:string,fn:()=>Promise<unknown>){setPending(name);setError('');try{await fn();setRuntime(await api<Runtime>('cast.status'));}catch(e){setError(e instanceof Error?e.message:String(e));}finally{if(alive.current)setPending('');}}
 async function apply(){await api('cast.settings.save',draft);if(editing){await api('cast.preview.end',{apply:true});editorActive.current=false;setEditing(false);}else if(runtime?.running&&captureDirty){await api('cast.stop');await api('cast.start');}await refresh();setSaved(true);setEpoch(v=>v+1);}
 async function beginFraming(){beforeFraming.current={horizontalFov:draft.horizontalFov,centerX:draft.centerX,centerY:draft.centerY};setRuntime(await api<Runtime>('cast.preview.start',draft));editorActive.current=true;setEditing(true);setEpoch(v=>v+1);}
 async function cancelFraming(){await api('cast.preview.end');editorActive.current=false;setEditing(false);if(beforeFraming.current)change(beforeFraming.current);setEpoch(v=>v+1);}
 useEffect(()=>{if(editing){const frame=requestAnimationFrame(()=>document.querySelector('.cast-framing-section')?.scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'}));return()=>cancelAnimationFrame(frame);}},[editing]);
 useEffect(()=>{if(page!=='casting-picture'&&editorActive.current)void action('preview',cancelFraming);},[page]);
 async function scan(){const token=++deviceScan.current;setSearched(true);for(let i=0;i<3;i++){const list=await api<Device[]>('cast.devices');if(token!==deviceScan.current||!alive.current)return;setDevices(list);if(i<2)await new Promise(resolve=>setTimeout(resolve,1000));}}
 useEffect(()=>{if(page==='casting-devices')void action('scan',scan);},[page]);
 async function copy(){const address=['localhost','127.0.0.1','[::1]'].includes(location.hostname)?runtime?.watchAddresses?.[0]??new URL('/cast/watch',location.origin).href:new URL('/cast/watch',location.origin).href;if(navigator.clipboard)await navigator.clipboard.writeText(address);else{const input=document.createElement('textarea');input.value=address;document.body.append(input);input.select();document.execCommand('copy');input.remove();}setCopied(true);setTimeout(()=>setCopied(false),2500);}
 const errorMessage=error||(page==='casting-receive'||page==='casting-devices'?runtime?.receiverError:runtime?.error);
 const presets=framePresets(aspect);
 function chooseAspect(value:number){const edge=Math.max(draft.width,draft.height);const size=value>=1?{width:edge,height:Math.round(edge/value/2)*2}:{width:Math.round(edge*value/2)*2,height:edge};change(size);}
 return <div className="casting cast-workspace">
  <header className="cast-page-heading"><div><h1>{t(titles[page][0])}</h1><p>{t(titles[page][1])}</p></div>{page==='casting'&&<span className={`cast-status ${runtime?.running?'live':''}`} role="status">{pending==='start'?t('正在启动…'):runtime?.running?t('正在串流'):t('未开始串流')}</span>}</header>
  {errorMessage&&<div className="cast-error" role="alert"><strong>{t('操作未完成')}</strong><p>{errorMessage}</p></div>}
  {page==='casting'&&<>
   <div className="cast-monitor"><CastVideo key={epoch} active={!!runtime?.running&&!runtime.preview} onError={setError}/>{!runtime?.running&&<div className="cast-monitor-empty"><IconDeviceVisionPro size={44} stroke={1.5}/><h2>{t('分享你看到的画面')}</h2><p>{t('启动后，手机和电脑可以通过网页实时观看。')}</p></div>}</div>
   <div className="cast-stream-bar"><div><strong>{t(config.source==='screen'?'屏幕采集':'SteamVR')}</strong><span>{config.width} × {config.height}<i/> {config.fps} fps</span></div><button className={runtime?.running?'':'primary'} disabled={busy||!runtime} onClick={()=>void action('start',async()=>{if(runtime?.running)await api('cast.stop');else{if(dirty)await apply();await api('cast.start');}setEpoch(v=>v+1);})}>{runtime?.running?<IconPlayerStop size={21}/>:<IconPlayerPlay size={21}/>}<span>{pending==='start'?t('正在启动…'):runtime?.running?t('停止串流'):t('开始串流')}</span></button></div>
   {runtime?.running&&<section className="cast-share"><div><IconWifi size={24}/><div><h2>{t('在其他设备上观看')}</h2><p>{t('连接同一网络，打开观看地址。')}</p></div></div><div className="cast-share-link"><code>{runtime.watchAddresses?.[0]??new URL('/cast/watch',location.origin).href}</code><button onClick={()=>void action('copy',copy)} aria-label={t('复制观看地址')}>{copied?<IconCheck size={20}/>:<IconCopy size={20}/>}<span>{copied?t('已复制'):t('复制')}</span></button><a className="cast-icon-link" href="/cast/watch" aria-label={t('打开观看网页')}><IconExternalLink size={21}/></a></div></section>}
   <details className="cast-disclosure"><summary>{t('网页访问设置')}</summary><NetworkSettings config={network} refresh={refresh}/></details>
  </>}
  {page==='casting-picture'&&<>
   <section className="cast-setting-section"><h2>{t('画面来源')}</h2><div className="cast-source-options" role="radiogroup" aria-label={t('采集方式')}>
    {([{value:'screen',label:'屏幕采集',description:'包含透视、Steam 菜单和空间窗口。',icon:IconDeviceVisionPro},{value:'steamVR',label:'SteamVR',description:'使用 SteamVR 提供的镜像画面。',icon:IconDeviceDesktop}] as const).map(option=><button key={option.value} role="radio" aria-checked={draft.source===option.value} className={draft.source===option.value?'selected':''} disabled={busy||editing} onClick={()=>change({source:option.value})}><option.icon size={28} stroke={1.6}/><span><strong>{t(option.label)}</strong><small>{t(option.description)}</small></span>{draft.source===option.value&&<IconCheck size={21}/>}</button>)}
   </div></section>
   {screen&&<section className="cast-setting-section"><h2>{t('输出画面')}</h2><Choices label={t('输出模式')} value={draft.output} disabled={busy||editing} options={[{value:'eye',label:t('单眼画面'),description:t('校正畸变，适合普通观看')},{value:'raw',label:t('双眼原始画面'),description:t('保留双眼布局和镜头畸变')}]} onChange={output=>change({output})}/></section>}
   {eye&&<section className="cast-setting-section cast-framing-section"><div className="cast-setting-title"><h2><IconCrop size={23}/>{t('取景')}</h2>{!editing&&<button disabled={busy} onClick={()=>void action('preview',beginFraming)}><IconCrop size={20}/>{pending==='preview'?t('正在连接画面…'):t('调整取景')}</button>}</div>
    {editing?<><FramingEditor key={epoch} settings={draft} view={runtime?.view??null} onChange={change} onError={setError}/><div className="cast-editor-actions"><p>{t('取景预览期间，共享画面会切换为完整视角。')}</p><button disabled={busy} onClick={()=>void action('preview',cancelFraming)}>{t('取消')}</button><button className="primary" disabled={busy||!runtime?.view} onClick={()=>void action('save',apply)}>{t('应用取景')}</button></div></>:<><div className="cast-framing-summary"><IconEye size={25}/><span>{draft.horizontalFov===null?t('完整视野'):t('已设置取景范围')}<small>{t('直接在实时画面上移动和缩放取景框。')}</small></span></div><h3>{t('主力眼')}</h3><Choices label={t('主力眼')} value={draft.eye} disabled={busy} options={[{value:'steamVR',label:t('跟随 SteamVR'),description:runtime?.dominantEye===0?t('当前：左眼'):runtime?.dominantEye===1?t('当前：右眼'):undefined},{value:'left',label:t('左眼')},{value:'right',label:t('右眼')}]} onChange={eye=>change({eye})}/></>}
   </section>}
   <section className="cast-setting-section"><h2>{t('画幅与分辨率')}</h2>{!(screen&&draft.output==='raw')&&<><h3>{t('画面比例')}</h3><div className="cast-ratio-options" role="radiogroup" aria-label={t('画面比例')}>{frameRatios.map(r=><button role="radio" aria-checked={ratio===r.label} className={ratio===r.label?'selected':''} disabled={busy} key={r.label} onClick={()=>chooseAspect(r.value)}><span className="cast-ratio-shape" style={{aspectRatio:r.value}}/><strong>{r.label}</strong></button>)}</div></>}
    {screen&&draft.output==='raw'&&<p className="cast-help">{t('原始双眼比例由头显屏幕决定。')}</p>}
    <h3>{t('分辨率')}</h3><div className="cast-resolution-options" role="radiogroup" aria-label={t('分辨率')}>{presets.map(size=><button role="radio" aria-checked={draft.width===size.width&&(draft.height===size.height||screen&&draft.output==='raw')} disabled={busy||size.width>4096||size.height>4096||size.width*size.height>8847360} className={draft.width===size.width&&(draft.height===size.height||screen&&draft.output==='raw')?'selected':''} key={size.width+'x'+size.height} onClick={()=>change(size)}><span>{size.width} × {size.height}</span></button>)}</div>
    {!presets.some(size=>size.width===draft.width&&size.height===draft.height)&&<p className="cast-help">{t('当前分辨率：{0} × {1}',{0:draft.width,1:draft.height})}</p>}
   </section>
   <section className="cast-setting-section"><h2>{t('流畅度与画质')}</h2><h3>{t('帧率')}</h3><Choices label={t('帧率')} value={draft.fps} disabled={busy} options={[24,30,60,90,120].map(fps=>({value:fps,label:`${fps} fps`}))} onChange={fps=>change({fps})}/><div className="cast-bitrate"><label htmlFor="cast-bitrate">{t('视频码率')}<output>{draft.bitrateMbps} Mbps</output></label><input id="cast-bitrate" type="range" min={1} max={80} step={1} value={draft.bitrateMbps} disabled={busy} onChange={e=>change({bitrateMbps:+e.target.value})}/><div><span>{t('更省带宽')}</span><span>{t('画面更清晰')}</span></div></div></section>
   <section className="cast-setting-section"><h2>{t('声音')}</h2><SwitchRow label={t('系统声音')} checked={draft.systemAudio} disabled={busy} onChange={systemAudio=>change({systemAudio})}/><SwitchRow label={t('麦克风')} checked={draft.microphone} disabled={busy} onChange={microphone=>change({microphone})}/></section>
  </>}
  {page==='casting-receive'&&<>
   <section className="cast-setting-section"><label className="cast-name-field"><span>{t('设备名称')}</span><input value={draft.receiverName} maxLength={80} disabled={busy} onChange={e=>change({receiverName:e.target.value})}/><small>{t('其他设备会在投屏列表中看到这个名称。')}</small></label></section>
   <div className="cast-protocols"><section><IconCast size={32} stroke={1.5}/><h2>AirPlay</h2><p>{t('接收一路音频或屏幕镜像。')}</p><SwitchRow label={t('AirPlay 接收')} checked={draft.airplay} disabled={busy} onChange={airplay=>change({airplay})}/></section><section><IconDeviceTv size={32} stroke={1.5}/><h2>DLNA</h2><p>{t('接收媒体播放地址，可打开多个窗口。')}</p><SwitchRow label={t('DLNA 接收')} checked={draft.dlna} disabled={busy} onChange={dlna=>change({dlna})}/></section></div>
   <p className="cast-consent-note"><IconCheck size={21}/>{t('收到投屏后先询问，接受后才打开播放器。')}</p>
   <section className="cast-setting-section"><h2>{t('当前投屏')}</h2>{runtime?.sessions?.length?<div className="cast-session-list">{runtime.sessions.map(session=><article key={session.id}>{session.width?<IconVideo size={25}/>:<IconMusic size={25}/>}<div><strong>{session.protocol}</strong><span>{session.accepted?t('正在播放'):t('等待确认')}</span></div>{session.accepted?<button disabled={busy} onClick={()=>void action('session',()=>api('cast.control',{id:session.id,action:'stop'}))}>{t('停止')}</button>:<><button className="primary" disabled={busy} onClick={()=>void action('session',()=>api('cast.control',{id:session.id,action:'accept'}))}>{t('打开')}</button><button disabled={busy} onClick={()=>void action('session',()=>api('cast.control',{id:session.id,action:'reject'}))}>{t('拒绝')}</button></>}</article>)}</div>:<div className="cast-empty-inline"><IconCast size={30}/><p>{t('还没有收到投屏')}</p><span>{t('开启接收后，在其他设备上选择 Framely。')}</span></div>}</section>
  </>}
  {page==='casting-devices'&&<>
   <div className="cast-device-toolbar"><span>{devices.length?t('找到 {0} 台设备',{0:devices.length}):t('附近设备')}</span><button disabled={busy} onClick={()=>void action('scan',scan)}><IconRefresh size={20}/>{pending==='scan'?t('正在查找…'):t('重新查找')}</button></div>
   {!network.enabled&&<div className="cast-context-note"><IconWifi size={23}/><span>{t('需要开启网页访问，设备才能读取投屏画面。')}</span><a href="#casting">{t('设置网页访问')}<IconArrowRight size={18}/></a></div>}
   {!runtime?.running&&<div className="cast-context-note"><IconPlayerPlay size={23}/><span>{t('先开始头显串流，再选择播放设备。')}</span><a href="#casting">{t('网页观看')}<IconArrowRight size={18}/></a></div>}
   {devices.length?<div className="cast-device-list">{devices.map(device=><article key={device.id}><div className="cast-device-icon"><IconDeviceTv size={32} stroke={1.5}/></div><div><h2>{device.name}</h2><span>{sending===device.id?t('正在投屏'):'DLNA'}</span></div><button className={sending===device.id?'':'primary'} disabled={busy||!runtime?.running||!network.enabled} onClick={()=>void action('send',async()=>{if(sending===device.id){await api('cast.send.stop',{id:device.id});setSending('');}else{await api('cast.send',{id:device.id});setSending(device.id);}})}>{sending===device.id?<IconPlayerStop size={20}/>:<IconCast size={20}/>}<span>{sending===device.id?t('停止投屏'):t('投到此设备')}</span></button></article>)}</div>:pending==='scan'?<div className="cast-device-skeleton" role="status" aria-label={t('正在查找设备')}>{[0,1,2].map(n=><div key={n}><span/><i/><b/></div>)}</div>:<div className="cast-empty"><IconDeviceTv size={52} stroke={1.4}/><h2>{searched?t('未找到播放设备'):t('查找附近设备')}</h2><p>{t('确认播放设备已开启 DLNA，并与头显连接同一网络。')}</p></div>}
  </>}
  {(page==='casting-picture'||page==='casting-receive')&&!editing&&<footer className="cast-save"><div><span role="status">{dirty?t('有未应用的修改'):saved?t('已应用'):t('设置已保存')}</span>{captureDirty&&runtime?.running&&<small>{t('应用后会重新启动串流。')}</small>}</div><button className="primary" disabled={busy||!dirty} onClick={()=>void action('save',apply)}>{pending==='save'?t('正在应用…'):t('应用修改')}</button></footer>}
 </div>;
}
