import React,{useEffect,useRef,useState} from 'react';
import {IconFolder,IconFile,IconArrowUp,IconRefresh,IconUpload,IconDownload,IconStar,IconTrash,IconChevronRight,IconChevronDown,IconSearch,IconFolderPlus,IconPlus,IconCopy,IconCut,IconClipboard,IconDots,IconPencil,IconX,IconArrowDown,IconHome,IconDeviceSdCard,IconFileText,IconPhoto,IconMovie,IconFileZip,IconExternalLink,IconInfoCircle,IconArrowLeft} from '@tabler/icons-react';
import {managerApi,ManagerError} from './manager-api';
import {api} from './api';
import {Select} from './localized-select';
import {SwitchRow} from './switch';
import {t} from './i18n';
import './manager-tools.css';
import './file-manager.css';
type Entry={name:string;path:string;directory:boolean;symlink:boolean;size:number;modified?:number;mode:number;uid:number;gid:number;linkTarget?:string};
type Listing={path:string;parent?:string;entries:Entry[];total:number;roots:{name:string;path:string}[]};
type Bookmark={name:string;path:string};
type Job={id:string;phase:string;bytes?:number;totalBytes?:number;completed?:number;total?:number;visited?:number;matches?:number;error?:string;result?:any};
type Dialog={title:string;kind:string;path?:string;name?:string;value?:string;entry?:Entry;files?:File[]};
function bytes(n:number){return n<1024?`${n} B`:n<1024**2?`${(n/1024).toFixed(1)} KiB`:n<1024**3?`${(n/1024**2).toFixed(1)} MiB`:`${(n/1024**3).toFixed(1)} GiB`;}
function FolderTree({name,path,onOpen,current,depth=0}:{name:string;path:string;onOpen:(path:string)=>void;current:string;depth?:number}){
 const[expanded,setExpanded]=useState(false),[children,setChildren]=useState<Entry[]>([]),[error,setError]=useState(''),[offset,setOffset]=useState(0),[more,setMore]=useState(false);
 const request=useRef(0),row=useRef<HTMLDivElement>(null);
 const ancestor=current!==path&&(path==='/'?current.startsWith('/'):current.startsWith(path+'/'));
 async function expand(next=0,follow=false){const id=++request.current;try{
  let page=next,entries:Entry[]=[],total=0;
  const childPath=ancestor?(path==='/'?'':path)+'/'+current.slice(path==='/'?1:path.length+1).split('/')[0]:'';
  do{const v=await managerApi<Listing>('files',{operation:'list',path,offset:page,hidden:true});if(id!==request.current)return;entries.push(...v.entries.filter(e=>e.directory));total=v.total;page+=200;}while(follow&&page<total&&!entries.some(e=>e.path===childPath));
  setChildren(previous=>next?[...previous,...entries]:entries);setOffset(page);setMore(total>page);setError('');setExpanded(true);
 }catch(e){if(id===request.current){setError(String(e));setExpanded(true);}}}
 useEffect(()=>{if(depth<20&&(depth===0||ancestor||current===path))void expand(0,ancestor);return()=>{request.current++;};},[path,current]);
 useEffect(()=>{if(current!==path||!row.current)return;const node=row.current,sidebar=node.closest<HTMLElement>('.file-tree-scroll');if(!sidebar)return;const a=node.getBoundingClientRect(),b=sidebar.getBoundingClientRect();if(a.top<b.top)sidebar.scrollTop+=a.top-b.top-8;else if(a.bottom>b.bottom)sidebar.scrollTop+=a.bottom-b.bottom+8;},[current,path]);
 return <div><div ref={row} className="file-side-entry file-tree-entry"><button className="file-tree-toggle" disabled={depth>=20} aria-expanded={expanded} aria-label={t(expanded?'收起文件夹':'展开文件夹')} onClick={()=>{if(expanded){request.current++;setExpanded(false);}else void expand();}}>{expanded?<IconChevronDown size={16}/>:<IconChevronRight size={16}/>}</button><button aria-current={current===path?'location':undefined} className={current===path?'active':''} onClick={()=>onOpen(path)}><IconFolder size={18}/><span>{name}</span></button></div>{error&&expanded&&<small>{error}</small>}{expanded&&<div className="file-tree">{children.map(e=><FolderTree key={e.path} name={e.name} path={e.path} current={current} onOpen={onOpen} depth={depth+1}/>)}{more&&<button onClick={()=>void expand(offset)}>{t('加载更多')}</button>}</div>}</div>;
}
export function FileManager({active=true}:{active?:boolean}){
 const[data,setData]=useState<Listing>({path:'',entries:[],total:0,roots:[]}),[path,setPath]=useState(''),[address,setAddress]=useState(''),[query,setQuery]=useState(''),[hidden,setHidden]=useState(false),[sort,setSort]=useState('name'),[descending,setDescending]=useState(false),[offset,setOffset]=useState(0),[selected,setSelected]=useState<string[]>([]),[bookmarks,setBookmarks]=useState<Bookmark[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[dialog,setDialog]=useState<Dialog|null>(null),[value,setValue]=useState(''),[policy,setPolicy]=useState('keep'),[permanent,setPermanent]=useState(false),[job,setJob]=useState<Job|null>(null),[clipboard,setClipboard]=useState<{paths:string[];cut:boolean}|null>(null),[preview,setPreview]=useState<{entry:Entry;url:string;video:boolean}|null>(null),[editor,setEditor]=useState<{path:string;text:string;revision:string}|null>(null),[modified,setModified]=useState(false),[trash,setTrash]=useState<any[]|null>(null),[upload,setUpload]=useState<{name:string;received:number;total:number}|null>(null),[results,setResults]=useState<any[]|null>(null),[counter,setCounter]=useState(0),[context,setContext]=useState(false),[bookmarkMenu,setBookmarkMenu]=useState<string|null>(null),[outcomes,setOutcomes]=useState<any[]>([]),[menu,setMenu]=useState<{x:number;y:number;blank:boolean}|null>(null);
 const layout=useRef<HTMLDivElement>(null),separator=useRef<HTMLDivElement>(null),menuElement=useRef<HTMLDivElement>(null),resize=useRef<{id:number;x:number;width:number;previous:string}|null>(null);
 const sidebarKey='framely-file-sidebar-width';
 function limitWidth(width:number){return Math.max(132,Math.min(width,480,(layout.current?.clientWidth??1200)*.4));}
 function setWidth(width:number,save=false){const node=layout.current;if(!node)return;const value=Math.round(limitWidth(width));node.style.setProperty('--file-sidebar-width',value+'px');separator.current?.setAttribute('aria-valuenow',String(value));if(save)try{localStorage.setItem(sidebarKey,String(value));}catch{}}
 function finishResize(event:React.PointerEvent<HTMLDivElement>,cancel=false){const drag=resize.current;if(!drag||drag.id!==event.pointerId)return;resize.current=null;layout.current?.classList.remove('is-resizing');if(cancel){if(drag.previous)layout.current?.style.setProperty('--file-sidebar-width',drag.previous);else layout.current?.style.removeProperty('--file-sidebar-width');}else setWidth(layout.current?.querySelector('aside')?.getBoundingClientRect().width??drag.width,true);if(event.currentTarget.hasPointerCapture(event.pointerId))event.currentTarget.releasePointerCapture(event.pointerId);}
 useEffect(()=>{const node=layout.current;if(!node)return;try{const saved=Number(localStorage.getItem(sidebarKey));if(Number.isFinite(saved)&&saved>=132&&saved<=480)node.style.setProperty('--file-sidebar-width',saved+'px');}catch{}const observer=new ResizeObserver(()=>{separator.current?.setAttribute('aria-valuenow',String(Math.round(node.querySelector('aside')?.getBoundingClientRect().width??224)));separator.current?.setAttribute('aria-valuemax',String(Math.floor(limitWidth(480))));});observer.observe(node);return()=>observer.disconnect();},[]);
 useEffect(()=>{if(!active)setMenu(null);},[active]);
 useEffect(()=>{if(!menu)return;const node=menuElement.current;if(!node)return;const bounds=node.getBoundingClientRect();node.style.left=Math.max(8,Math.min(menu.x,window.innerWidth-bounds.width-8))+'px';node.style.top=Math.max(8,Math.min(menu.y,window.innerHeight-bounds.height-8))+'px';node.querySelector<HTMLButtonElement>('button:not(:disabled)')?.focus();const dismiss=(event:Event)=>{if(!node.contains(event.target as Node))setMenu(null);};window.addEventListener('pointerdown',dismiss,true);window.addEventListener('scroll',dismiss,true);window.addEventListener('resize',dismiss);return()=>{window.removeEventListener('pointerdown',dismiss,true);window.removeEventListener('scroll',dismiss,true);window.removeEventListener('resize',dismiss);};},[menu]);
 function showMenu(event:React.MouseEvent,entry?:Entry){event.preventDefault();event.stopPropagation();setContext(false);if(entry){if(!selected.includes(entry.path))setSelected([entry.path]);}else setSelected([]);setMenu({x:event.clientX,y:event.clientY,blank:!entry});}
 const fileInput=useRef<HTMLInputElement>(null),directoryInput=useRef<HTMLInputElement>(null),sequence=useRef(0),cancelUpload=useRef(false),jobId=useRef('');
 useEffect(()=>{if(!modified)return;const guard=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue='';};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard);},[modified]);
 useEffect(()=>{if(!active)return;const back=(event:Event)=>{if(event instanceof KeyboardEvent&&event.key!=='Escape')return;if(menu){setMenu(null);}else if(dialog){setDialog(null);}else if(preview){setPreview(null);}else if(editor){if(modified)openDialog({title:t('未保存的修改'),kind:'editor.discard'});else setEditor(null);}};window.addEventListener('keydown',back);window.addEventListener('framely.back',back);return()=>{window.removeEventListener('keydown',back);window.removeEventListener('framely.back',back);};},[active,menu,dialog,preview,editor,modified]);
 const refresh=()=>setCounter(n=>n+1);
 function navigate(next:string){setMenu(null);setError('');setData(previous=>({...previous,path:next,entries:[],total:0,parent:next==='/'?undefined:next.replace(/\/?[^/]+\/?$/,'')||'/'}));setLoading(true);setPath(next);setAddress(next);setSelected([]);setOffset(0);setResults(null);setQuery('');setTrash(null);setContext(false);}
 useEffect(()=>{let live=true;managerApi<Bookmark[]>('files',{operation:'preferences'}).then(v=>{if(live)setBookmarks(v);}).catch(e=>setError(String(e)));return()=>{live=false;};},[]);
 useEffect(()=>{const seq=++sequence.current;setLoading(true);const timer=setTimeout(()=>{managerApi<Listing>('files',{operation:'list',path:path||undefined,query,hidden,sort,descending,offset}).then(v=>{if(seq!==sequence.current)return;setData(v);setAddress(v.path);setLoading(false);if(path!==v.path)setPath(v.path);}).catch(e=>{if(seq===sequence.current){setError(String(e));setLoading(false);setSelected([]);setData(previous=>({...previous,entries:[],total:0}));}});},120);return()=>clearTimeout(timer);},[path,query,hidden,sort,descending,offset,counter]);
 useEffect(()=>setSelected([]),[query,offset,sort,descending,hidden]);
 const shown=results??data.entries;
 async function saveBookmarks(next:Bookmark[]){try{await managerApi('files',{operation:'preferences',value:next});setBookmarks(next);}catch(e){setError(String(e));throw e;}}
 function openDialog(d:Dialog){setMenu(null);setDialog(d);setValue(d.value??d.name??'');setPolicy('keep');setPermanent(false);setContext(false);}
 async function perform(p:any){setError('');setBusy(true);try{const result=await managerApi('files',p);if(result.job){jobId.current=result.job;for(;;){const v=await api<Job>('job.status',{job:result.job});setJob(v);if(v.phase==='done'){jobId.current='';if(v.result?.items){setOutcomes(v.result.items);const errors=v.result.items.filter((i:any)=>i.error);if(errors.length)setError(errors.map((i:any)=>`${i.path}: ${i.error}`).join('\n'));}return v.result;}if(v.phase==='failed'||v.phase==='cancelled'){jobId.current='';throw new Error(v.error??t('任务已取消'));}await new Promise(r=>setTimeout(r,200));}}return result;}catch(e){setError(String(e));throw e;}finally{setBusy(false);refresh();}}
 async function run(p:any){try{await perform(p);}catch{}}
 function download(url:string){const a=document.createElement('a');a.href=url;a.download='';document.body.appendChild(a);a.click();a.remove();}
 async function getDownload(paths=selected){try{if(paths.length===1&&!shown.find(e=>e.path===paths[0])?.directory){const v=await perform({operation:'download',path:paths[0]});download(v.url);}else{const v=await perform({operation:'download.batch',paths});download(v.url);}}catch{}}
 async function open(e:Entry){if(e.directory){navigate(e.path);return;}const ext=e.name.split('.').pop()?.toLowerCase()??'';if(['png','jpg','jpeg','gif','webp','avif','bmp','mp4','webm','mov','m4v'].includes(ext)){try{const v=await perform({operation:'preview',path:e.path});setPreview({entry:e,url:v.url,video:['mp4','webm','mov','m4v'].includes(ext)});}catch{}return;}try{const v=await perform({operation:'read',path:e.path});setEditor({path:e.path,...v});setModified(false);}catch{openDialog({title:t('文件属性'),kind:'properties',entry:e,value:e.mode.toString(8)});}}
 async function uploads(files:File[]){setBusy(true);cancelUpload.current=false;let id='';try{let total=files.reduce((n,f)=>n+f.size,0),received=0;for(const file of files){if(cancelUpload.current)break;const relative=file.webkitRelativePath||file.name;id=(await managerApi('files',{operation:'upload.start',directory:path,name:relative,size:file.size,conflict:policy})).id;setUpload({name:relative,received,total});for(let offset=0;offset<file.size;offset+=1024*1024){if(cancelUpload.current)throw new Error(t('任务已取消'));const chunk=file.slice(offset,offset+1024*1024);const r=await fetch(`/manager-api/file-upload/${id}/${offset}`,{method:'POST',body:chunk});if(r.status===401){location.replace('/manager');throw new Error(t('请重新登录'));}if(!r.ok)throw new Error(t('服务请求失败：{0}',{0:r.status}));const v=await r.json();if(v.error)throw new Error(t(v.error));received+=chunk.size;setUpload({name:relative,received,total});}if(cancelUpload.current)throw new Error(t('任务已取消'));await managerApi('files',{operation:'upload.finish',id,approve:policy==='overwrite'});id='';}}catch(e){setError(String(e));if(id)await managerApi('files',{operation:'upload.cancel',id}).catch(()=>{});}finally{setBusy(false);setUpload(null);refresh();}}
 async function submit(){if(!dialog)return;const d=dialog;if(['delete','paste','compress','extract'].includes(d.kind))setDialog(null);try{
  if(d.kind==='bookmark'){const next=[...bookmarks.filter(b=>b.path!==d.path),{name:value,path:d.path!}];await saveBookmarks(next);}
  else if(d.kind==='bookmark.rename'){await saveBookmarks(bookmarks.map(b=>b.path===d.path?{...b,name:value}:b));}
  else if(d.kind==='create'||d.kind==='folder'){await perform({operation:'create',directory:path,name:value,folder:d.kind==='folder'});}
  else if(d.kind==='rename'){await perform({operation:'rename',path:d.path,name:value});}
  else if(d.kind==='delete'){await perform({operation:'delete',paths:selected,permanent,approve:permanent});setSelected([]);}
  else if(d.kind==='paste'){await perform({operation:clipboard?.cut?'move':'copy',paths:clipboard?.paths,destination:path,conflict:policy,approve:policy==='overwrite'});if(clipboard?.cut)setClipboard(null);}
  else if(d.kind==='properties'){await perform({operation:'chmod',path:d.entry!.path,mode:parseInt(value,8)});}
  else if(d.kind==='compress'){const format=value.endsWith('.tar.gz')?'tar.gz':value.endsWith('.tar')?'tar':'zip';await perform({operation:'compress',paths:selected,path:path+'/'+value,format,conflict:policy,approve:policy==='overwrite'});}
  else if(d.kind==='extract'){await perform({operation:'extract',path:d.path,destination:value,conflict:policy,approve:policy==='overwrite'});}
  else if(d.kind==='trash.purge'){await perform({operation:'trash.purge',id:d.path,all:!d.path,approve:true});setTrash(await managerApi('files',{operation:'trash.list'}));}
  else if(d.kind==='trash.restore'){await perform({operation:'trash.restore',id:d.path,conflict:policy,approve:policy==='overwrite'});setTrash(await managerApi('files',{operation:'trash.list'}));}
  else if(d.kind==='upload'){setDialog(null);await uploads(d.files??[]);return;}
  else if(d.kind==='editor.discard'){setEditor(null);setModified(false);}
  else if(d.kind==='editor.overwrite'){const v=await perform({operation:'write',...editor,approve:true});setEditor(e=>e?{...e,...v}:null);setModified(false);}
  setDialog(null);
 }catch{}}
 async function saveText(){if(!editor)return;try{const v=await perform({operation:'write',...editor});setEditor(e=>e?{...e,...v}:null);setModified(false);}catch(e){if((e instanceof ManagerError?e.raw:String(e)).includes('File changed outside the editor'))openDialog({title:t('保存冲突'),kind:'editor.overwrite'});}}
 const picked=shown.find(e=>e.path===selected[0]);
 const selectedCount=selected.length;
 const bookmarkCurrent=bookmarks.some(b=>b.path===path);
 const fileKind=(entry:Entry)=>entry.directory?t('文件夹'):entry.name.split('.').length>1?entry.name.split('.').pop()!.toUpperCase():t('文件');
 const formatDate=(seconds?:number)=>seconds?new Date(seconds*1000).toLocaleString(document.documentElement.lang,{year:'numeric',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):'-';
 const actions=<>
  <button role={menu?'menuitem':undefined} disabled={!selectedCount||busy} onClick={()=>{setClipboard({paths:selected,cut:false});setContext(false);}}><IconCopy size={18}/>{t('复制')}</button>
  <button role={menu?'menuitem':undefined} disabled={!selectedCount||busy} onClick={()=>{setClipboard({paths:selected,cut:true});setContext(false);}}><IconCut size={18}/>{t('剪切')}</button>
  <button role={menu?'menuitem':undefined} disabled={selectedCount!==1||!picked||busy||loading} onClick={()=>openDialog({title:t('重命名'),kind:'rename',path:selected[0],value:picked?.name})}><IconPencil size={18}/>{t('重命名')}</button>
  <button role={menu?'menuitem':undefined} disabled={!selectedCount||busy} onClick={()=>openDialog({title:t('删除文件'),kind:'delete'})}><IconTrash size={18}/>{t('删除')}</button>
  <button role={menu?'menuitem':undefined} disabled={selectedCount!==1||!picked||busy||loading} onClick={()=>openDialog({title:t('文件属性'),kind:'properties',entry:picked,value:picked?.mode.toString(8)})}><IconInfoCircle size={18}/>{t('属性')}</button>
  <button role={menu?'menuitem':undefined} disabled={!selectedCount||busy} onClick={()=>openDialog({title:t('创建压缩包'),kind:'compress',value:'archive.zip'})}><IconFileZip size={18}/>{t('压缩')}</button>
  <button role={menu?'menuitem':undefined} disabled={selectedCount!==1||!picked||busy||loading} onClick={()=>openDialog({title:t('解压文件'),kind:'extract',path:selected[0],value:path})}><IconFolder size={18}/>{t('解压')}</button>
  <button role={menu?'menuitem':undefined} disabled={selectedCount!==1||!picked||busy||loading} onClick={()=>void open(picked!)}><IconExternalLink size={18}/>{t('打开')}</button>
 </>;
 return <section className="manager-tool file-manager">
 <input ref={fileInput} type="file" multiple hidden onChange={e=>{if(e.target.files)openDialog({title:t('上传文件'),kind:'upload',files:Array.from(e.target.files)});e.target.value='';}}/><input ref={directoryInput} type="file" multiple hidden {...{'webkitdirectory':''} as any} onChange={e=>{if(e.target.files)openDialog({title:t('上传文件夹'),kind:'upload',files:Array.from(e.target.files)});e.target.value='';}}/>
 {error&&<div role="alert" className="file-notice file-notice-error"><IconInfoCircle size={20}/><span>{error}</span><button aria-label={t('关闭')} onClick={()=>setError('')}><IconX size={18}/></button></div>}
 {upload&&<div className="file-notice file-progress"><IconUpload size={20}/><span>{upload.name}</span><progress value={upload.received} max={upload.total}/><span>{bytes(upload.received)} / {bytes(upload.total)}</span><button onClick={()=>cancelUpload.current=true}>{t('取消')}</button></div>}
 {job&&<div className="file-notice file-progress"><span>{t(job.phase)}</span>{job.totalBytes?<progress value={job.bytes??0} max={job.totalBytes}/>:<progress/>}<span>{job.total?`${job.completed??0}/${job.total}`:job.visited?`${job.visited} · ${job.matches??0}`:job.bytes?bytes(job.bytes):''}</span>{!['done','failed','cancelled'].includes(job.phase)?<button onClick={()=>void api('job.cancel',{job:job.id}).catch(e=>setError(String(e)))}>{t('取消')}</button>:<button aria-label={t('关闭')} onClick={()=>setJob(null)}><IconX size={18}/></button>}</div>}
 {outcomes.length>0&&<details className="file-outcomes"><summary>{t('逐项结果')} · {outcomes.length}</summary>{outcomes.map((item,index)=><p key={index}>{item.path} · {item.error??t(item.result?.skipped||item.skipped?'已跳过':'已完成')}</p>)}</details>}
 <div className="file-layout" ref={layout}>
 <aside className="file-sidebar" aria-label={t('文件导航')}>
 <section className="file-quick-access"><h3>{t('快速访问')}</h3><div className="file-quick-access-list">
 {data.roots.filter(root=>root.name!=='Filesystem').map(root=><button key={root.name+root.path} className={!trash&&path===root.path?'active':''} onClick={()=>navigate(root.path)}>{root.name==='Home'?<IconHome size={18}/>:root.name==='Downloads'?<IconDownload size={18}/>:<IconDeviceSdCard size={18}/>}<span>{t(root.name)}</span></button>)}
 {bookmarks.map((bookmark,index)=><div className="file-bookmark" key={bookmark.path}><div className="file-side-entry"><button className={!trash&&path===bookmark.path?'active':''} onClick={()=>navigate(bookmark.path)}><IconStar size={18}/><span>{bookmark.name}</span></button><button className="file-bookmark-more" aria-label={t('快捷入口操作')} aria-expanded={bookmarkMenu===bookmark.path} onClick={()=>setBookmarkMenu(v=>v===bookmark.path?null:bookmark.path)}><IconDots size={16}/></button></div>
 {bookmarkMenu===bookmark.path&&<div className="file-bookmark-actions"><button disabled={index===0} aria-label={t('上移快捷入口')} onClick={()=>{const next=[...bookmarks];[next[index-1],next[index]]=[next[index],next[index-1]];void saveBookmarks(next);}}><IconArrowUp size={16}/></button><button disabled={index===bookmarks.length-1} aria-label={t('下移快捷入口')} onClick={()=>{const next=[...bookmarks];[next[index+1],next[index]]=[next[index],next[index+1]];void saveBookmarks(next);}}><IconArrowDown size={16}/></button><button aria-label={t('重命名快捷入口')} onClick={()=>openDialog({title:t('重命名快捷入口'),kind:'bookmark.rename',path:bookmark.path,value:bookmark.name})}><IconPencil size={16}/></button><button aria-label={t('移除快捷入口')} onClick={()=>void saveBookmarks(bookmarks.filter(v=>v.path!==bookmark.path))}><IconX size={16}/></button></div>}</div>)}
 <button className={trash?'active':''} onClick={()=>{setContext(false);void managerApi<any[]>('files',{operation:'trash.list'}).then(setTrash).catch(e=>setError(String(e)));}}><IconTrash size={18}/><span>{t('回收站')}</span></button></div></section>
 <section className="file-directory-tree"><h3>{t('目录树')}</h3><div className="file-tree-scroll"><FolderTree name="/" path="/" current={trash?'':path} onOpen={navigate}/></div></section>
 </aside>
 <div ref={separator} className="file-sidebar-resizer" role="separator" aria-orientation="vertical" aria-label={t('调整侧栏宽度')} aria-valuemin={132} aria-valuemax={480} aria-valuenow={224} tabIndex={0} data-framely-no-scroll-drag onPointerDown={event=>{if(event.button!==0)return;event.preventDefault();setMenu(null);const node=layout.current;if(!node)return;resize.current={id:event.pointerId,x:event.clientX,width:node.querySelector('aside')!.getBoundingClientRect().width,previous:node.style.getPropertyValue('--file-sidebar-width')};node.classList.add('is-resizing');event.currentTarget.setPointerCapture(event.pointerId);}} onPointerMove={event=>{const drag=resize.current;if(drag?.id===event.pointerId)setWidth(drag.width+event.clientX-drag.x);}} onPointerUp={event=>finishResize(event)} onPointerCancel={event=>finishResize(event,true)} onLostPointerCapture={()=>{resize.current=null;layout.current?.classList.remove('is-resizing');}} onKeyDown={event=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;event.preventDefault();event.stopPropagation();const width=layout.current?.querySelector('aside')?.getBoundingClientRect().width??224;setWidth(event.key==='Home'?132:event.key==='End'?480:width+(event.key==='ArrowRight'?10:-10),true);}}/>
 <div className="file-main">
 <div className="file-location"><button className="file-icon-button" aria-label={t('上级目录')} disabled={!data.parent||!!trash} onClick={()=>navigate(data.parent!)}><IconArrowUp size={18}/></button><label className="file-address"><span className="file-sr-only">{t('文件路径')}</span><IconFolder size={18}/><input aria-label={t('文件路径')} value={address} onChange={e=>setAddress(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')navigate(address);}}/></label><button className="file-icon-button" aria-label={t('刷新')} onClick={refresh}><IconRefresh size={18}/></button><button className={`file-icon-button ${bookmarkCurrent?'is-bookmarked':''}`} aria-label={t('添加到快速访问')} disabled={!path||!!trash} onClick={()=>openDialog({title:t('添加到快速访问'),kind:'bookmark',path,value:path.split('/').pop()||'/'})}><IconStar size={18}/></button></div>
 <div className="file-directory-heading"><div><div className="file-breadcrumbs" aria-label={t('文件路径')}><button onClick={()=>navigate('/')}>/</button>{path.split('/').filter(Boolean).map((part,index,parts)=><React.Fragment key={index}><IconChevronRight size={13}/><button onClick={()=>navigate('/'+parts.slice(0,index+1).join('/'))}>{part}</button></React.Fragment>)}</div></div><span className="file-item-count">{t('共 {0} 项',{0:results?results.length:data.total})}</span></div>
 {trash?<div className="file-trash-content"><div className="file-command-bar"><button onClick={()=>setTrash(null)}><IconArrowLeft size={18}/>{t('返回文件')}</button><button className="danger" disabled={!trash.length||busy} onClick={()=>openDialog({title:t('清空回收站'),kind:'trash.purge'})}><IconTrash size={18}/>{t('清空回收站')}</button></div><p className="file-hint">{t('回收站文件保留 30 天，到期自动删除。')}</p>{!trash.length&&<div className="file-empty"><IconTrash size={40}/><h3>{t('回收站为空')}</h3></div>}{trash.map(item=><div className="file-trash-item" key={item.id}><IconFile size={24}/><div><b>{item.name}</b><p>{item.path}</p><small>{t('到期时间')}：{formatDate(item.expires)}</small></div><div className="file-actions"><button onClick={()=>openDialog({title:t('恢复文件'),kind:'trash.restore',path:item.id})}>{t('恢复')}</button><button className="danger" onClick={()=>openDialog({title:t('永久删除'),kind:'trash.purge',path:item.id})}>{t('永久删除')}</button></div></div>)}</div>:<>
 <div className="file-command-bar"><div className="file-actions"><button disabled={busy} onClick={()=>openDialog({title:t('新建文件夹'),kind:'folder'})}><IconFolderPlus size={18}/>{t('新建文件夹')}</button><button disabled={busy} onClick={()=>openDialog({title:t('新建文件'),kind:'create'})}><IconPlus size={18}/>{t('新建文件')}</button><button disabled={!clipboard||busy} onClick={()=>openDialog({title:t('粘贴文件'),kind:'paste'})}><IconClipboard size={18}/>{t('粘贴')}</button></div><div className="file-actions"><button className="file-primary" disabled={busy} onClick={()=>fileInput.current?.click()}><IconUpload size={18}/>{t('上传文件')}</button>
 <button disabled={busy} onClick={()=>directoryInput.current?.click()}><IconFolderPlus size={18}/>{t('上传文件夹')}</button>
 <button disabled={!selectedCount||busy} onClick={()=>void getDownload()}><IconDownload size={18}/>{t('下载文件')}</button><button className={context?'active':''} aria-expanded={context} onClick={()=>setContext(v=>!v)}><IconDots size={18}/>{t('操作')}</button></div></div>
 {context&&<div className="file-operation-panel">{actions}</div>}
 <div className="file-filter-bar"><label className="file-search"><span className="file-sr-only">{t('搜索文件')}</span><IconSearch size={18}/><input aria-label={t('搜索文件')} placeholder={t('搜索当前目录')} value={query} onChange={e=>{setQuery(e.target.value);setOffset(0);setResults(null);}}/>{query&&<button className="file-icon-button" aria-label={t('清除选择')} onClick={()=>{setQuery('');setResults(null);}}><IconX size={16}/></button>}</label><button disabled={!query||busy} onClick={()=>void perform({operation:'search',path,query}).then(v=>{setResults(v.entries);setSelected([]);}).catch(()=>{})}>{t('搜索子目录')}</button><div className="file-sort"><Select label={t('排序')} value={sort} onChange={setSort} options={[{value:'name',label:t('名称')},{value:'size',label:t('大小')},{value:'modified',label:t('修改时间')}]}/><button className="file-icon-button" aria-label={t(descending?'降序':'升序')} onClick={()=>setDescending(v=>!v)}>{descending?<IconArrowDown size={18}/>:<IconArrowUp size={18}/>}</button></div><SwitchRow label={t('显示隐藏文件')} checked={hidden} onChange={setHidden}/></div>
 <div className="file-list-scroll" aria-busy={loading} onContextMenu={event=>showMenu(event)}><table className="file-table"><thead><tr><th className="file-check"><input type="checkbox" aria-label={t('选择本页')} checked={shown.length>0&&shown.every(entry=>selected.includes(entry.path))} onChange={event=>setSelected(event.target.checked?shown.map(entry=>entry.path):[])}/></th><th>{t('名称')}</th><th className="file-kind">{t('类型')}</th><th className="file-size">{t('大小')}</th><th className="file-time">{t('修改时间')}</th></tr></thead><tbody>
 {loading&&!shown.length?Array.from({length:5},(_,index)=><tr className="file-skeleton" key={index} aria-hidden="true"><td/><td><i/></td><td className="file-kind"><i/></td><td className="file-size"><i/></td><td className="file-time"><i/></td></tr>):shown.map(entry=><tr key={entry.path} className={selected.includes(entry.path)?'selected':''} onContextMenu={event=>showMenu(event,entry)}><td className="file-check"><input type="checkbox" aria-label={entry.name} checked={selected.includes(entry.path)} onChange={event=>setSelected(v=>event.target.checked?[...new Set([...v,entry.path])]:v.filter(p=>p!==entry.path))}/></td><td><button className="file-name" onClick={()=>void open(entry)}><span className={`file-entry-icon ${entry.directory?'folder':''}`}>{entry.directory?<IconFolder size={22}/>:['png','jpg','jpeg','gif','webp','avif','bmp'].includes(entry.name.split('.').pop()?.toLowerCase()??'')?<IconPhoto size={22}/>:['mp4','webm','mov','m4v'].includes(entry.name.split('.').pop()?.toLowerCase()??'')?<IconMovie size={22}/>:['zip','tar','gz'].includes(entry.name.split('.').pop()?.toLowerCase()??'')?<IconFileZip size={22}/>:<IconFileText size={22}/>}</span><span>{entry.name}</span>{entry.symlink&&<IconExternalLink size={14}/>}</button></td><td className="file-kind">{fileKind(entry)}</td><td className="file-size">{entry.directory?'-':bytes(entry.size)}</td><td className="file-time">{formatDate(entry.modified)}</td></tr>)}</tbody></table>
 {!loading&&!shown.length&&<div className="file-empty"><IconFolder size={40}/><h3>{t(query?'没有匹配的文件':'此文件夹为空')}</h3><p>{t(query?'试试其他名称，或搜索子目录。':'上传文件或新建文件夹。')}</p></div>}</div>
 <footer className="file-status-bar"><span>{selectedCount?t('已选择 {0} 项',{0:selectedCount}):t('共 {0} 项',{0:results?results.length:data.total})}{clipboard&&<small>{t(clipboard.cut?'已剪切 {0} 项':'已复制 {0} 项',{0:clipboard.paths.length})}</small>}</span>{!results&&<div className="file-pagination"><button className="file-icon-button" aria-label={t('上一页')} disabled={offset===0} onClick={()=>setOffset(v=>Math.max(0,v-200))}><IconChevronRight className="file-chevron-back" size={18}/></button><span>{Math.floor(offset/200)+1} / {Math.max(1,Math.ceil(data.total/200))}</span><button className="file-icon-button" aria-label={t('下一页')} disabled={offset+200>=data.total} onClick={()=>setOffset(v=>v+200)}><IconChevronRight size={18}/></button></div>}</footer>
 </>}
 </div></div>
 {active&&menu&&<div ref={menuElement} className="file-context-menu" role="menu" aria-label={t('文件操作')} style={{left:menu.x,top:menu.y}} onContextMenu={event=>event.preventDefault()} onClick={event=>{if((event.target as HTMLElement).closest('button:not(:disabled)'))setMenu(null);}} onKeyDown={event=>{const buttons=Array.from(event.currentTarget.querySelectorAll<HTMLButtonElement>('button:not(:disabled)'));if(['ArrowDown','ArrowUp','Home','End'].includes(event.key)){event.preventDefault();const index=buttons.indexOf(document.activeElement as HTMLButtonElement),next=event.key==='Home'?0:event.key==='End'?buttons.length-1:(index+(event.key==='ArrowDown'?1:-1)+buttons.length)%buttons.length;buttons[next]?.focus();}if(event.key==='Escape')setMenu(null);}}>
 {menu.blank?<><button role="menuitem" disabled={busy} onClick={()=>openDialog({title:t('新建文件夹'),kind:'folder'})}><IconFolderPlus size={18}/>{t('新建文件夹')}</button><button role="menuitem" disabled={busy} onClick={()=>openDialog({title:t('新建文件'),kind:'create'})}><IconPlus size={18}/>{t('新建文件')}</button><button role="menuitem" disabled={!clipboard||busy} onClick={()=>openDialog({title:t('粘贴文件'),kind:'paste'})}><IconClipboard size={18}/>{t('粘贴')}</button><div role="separator"/><button role="menuitem" disabled={busy} onClick={()=>fileInput.current?.click()}><IconUpload size={18}/>{t('上传文件')}</button><button role="menuitem" disabled={busy} onClick={()=>directoryInput.current?.click()}><IconFolderPlus size={18}/>{t('上传文件夹')}</button><button role="menuitem" onClick={refresh}><IconRefresh size={18}/>{t('刷新')}</button></>:<>{actions}<div role="separator"/><button role="menuitem" disabled={!selectedCount||busy} onClick={()=>void getDownload()}><IconDownload size={18}/>{t('下载文件')}</button>{picked?.directory&&selectedCount===1&&<button role="menuitem" disabled={busy} onClick={()=>openDialog({title:t('添加到快速访问'),kind:'bookmark',path:picked.path,value:picked.name})}><IconStar size={18}/>{t('添加到快速访问')}</button>}</>}
 </div>}
 {active&&dialog&&<div className="modal" role="dialog" aria-modal="true" aria-label={dialog.title}><h2>{dialog.title}</h2>{error&&<p className="error">{error}</p>}{dialog.kind==='properties'&&dialog.entry&&<div className="file-details"><p>{dialog.entry.path}</p><p>{bytes(dialog.entry.size)} · UID {dialog.entry.uid} / GID {dialog.entry.gid}</p>{dialog.entry.linkTarget&&<p>{dialog.entry.linkTarget}</p>}</div>}{['create','folder','rename','bookmark','bookmark.rename','compress','extract','properties'].includes(dialog.kind)&&<label>{t(dialog.kind==='properties'?'权限（八进制）':dialog.kind==='extract'?'目标目录':'名称')}<input autoFocus value={value} onChange={e=>setValue(e.target.value)}/></label>}
 {dialog.kind==='delete'&&<><p>{t('请选择删除方式。')}</p><Select label={t('删除方式')} value={permanent?'permanent':'trash'} onChange={v=>setPermanent(v==='permanent')} options={[{value:'trash',label:t('移至回收站（30 天）')},{value:'permanent',label:t('永久删除')}]}/>{permanent&&<p>{t('永久删除无法撤销。')}</p>}</>}
 {['paste','upload','compress','extract','trash.restore'].includes(dialog.kind)&&<><p>{t('遇到同名文件时')}</p><Select label={t('同名处理')} value={policy} onChange={setPolicy} options={[{value:'keep',label:t('保留两份')},{value:'skip',label:t('跳过')},...(dialog.kind==='trash.restore'?[]:[{value:'overwrite',label:t('覆盖')}])]}/>{policy==='overwrite'&&<p>{t('确认后会覆盖同名文件或整个同名文件夹。')}</p>}</>}{dialog.kind==='compress'&&<p>{t('支持 .zip、.tar 和 .tar.gz。')}</p>}{dialog.kind==='trash.purge'&&<p>{t('永久删除无法撤销。')}</p>}{dialog.kind==='editor.discard'&&<p>{t('关闭将丢弃未保存的修改。')}</p>}{dialog.kind==='editor.overwrite'&&<p>{t('文件已被外部修改。可重新加载，或确认覆盖。')}</p>}
 <footer>{dialog.kind==='editor.overwrite'&&<button onClick={()=>void perform({operation:'read',path:editor?.path}).then(v=>{setEditor(e=>e?{...e,...v}:null);setModified(false);setDialog(null);}).catch(()=>{})}>{t('重新加载')}</button>}<button disabled={busy} onClick={()=>setDialog(null)}>{t('取消')}</button><button disabled={busy} className={permanent||dialog.kind==='trash.purge'?'danger':'primary'} onClick={()=>void submit()}>{t('确认')}</button></footer></div>}
 {active&&preview&&<div className="modal file-preview" role="dialog" aria-modal="true" aria-label={preview.entry.name}><h2>{preview.entry.name}</h2>{error&&<p className="error">{error}</p>}{preview.video?<video src={preview.url} controls playsInline onError={()=>setError(t('浏览器无法播放此格式，请下载后打开。'))}/>:<img src={preview.url} alt={preview.entry.name} onError={()=>setError(t('浏览器无法预览此格式，请下载后打开。'))}/>}<footer><button onClick={()=>void getDownload([preview.entry.path])}>{t('下载文件')}</button><button onClick={()=>setPreview(null)}>{t('关闭')}</button></footer></div>}
 {active&&editor&&!dialog&&<div className="modal file-editor-modal" role="dialog" aria-modal="true"><h2>{editor.path.split('/').pop()}{modified?' *':''}</h2>{error&&<p className="error">{error}</p>}<textarea aria-label={t('文本内容')} className="file-editor" value={editor.text} onChange={e=>{setEditor(v=>v?{...v,text:e.target.value}:null);setModified(true);}}/><footer><button disabled={busy} onClick={()=>void saveText()}>{t('保存')}</button><button onClick={()=>{if(!modified)setEditor(null);else openDialog({title:t('未保存的修改'),kind:'editor.discard'});}}>{t('关闭')}</button></footer></div>}
 </section>;
}
