import React,{useState} from 'react';
import {IconUpload,IconX,IconRefresh,IconFolder} from '@tabler/icons-react';
import {FileUploadQueue} from './file-upload-queue';
import {Select} from './localized-select';
import {t} from './i18n';
export const uploadBytes=(n:number)=>n<1024?`${n} B`:n<1024**2?`${(n/1024).toFixed(1)} KiB`:n<1024**3?`${(n/1024**2).toFixed(1)} MiB`:`${(n/1024**3).toFixed(1)} GiB`;
const labels={waiting:'等待上传',uploading:'正在上传',done:'已完成',skipped:'已跳过',failed:'上传失败',cancelled:'已取消'};
export function FileUploadPanel({queue,limit,onLimit}:{queue:FileUploadQueue;limit:number;onLimit:(n:number)=>void}){
 const [visible,setVisible]=useState<Record<string,number>>({});
 const tasks=queue.batches.flatMap(b=>b.tasks),pending=tasks.filter(t=>t.state==='waiting'||t.state==='uploading').length;
 return <details className="file-upload-queue" open={tasks.length>0}><summary><IconUpload size={18}/><span>{t('上传任务队列')} · {t('{0} 项进行中 · 共 {1} 项',{0:pending,1:tasks.length})}</span><span>{uploadBytes(tasks.reduce((n,t)=>n+t.received,0))}</span></summary><div className="file-upload-controls"><div className="file-upload-limit"><span>{t('同时上传文件数')}</span><Select label={t('同时上传文件数')} value={String(limit)} onChange={n=>onLimit(Number(n))} options={Array.from({length:8},(_,i)=>({value:String(i+1),label:String(i+1)}))}/></div><button onClick={()=>queue.clear()}>{t('清除已结束记录')}</button></div>
 <div className="file-upload-batches">{queue.batches.map(batch=><section key={batch.id}><header><span title={batch.directory}>{batch.directory}</span><button disabled={!batch.tasks.some(t=>t.state==='failed')} onClick={()=>queue.retry(undefined,batch.id)} aria-label={t('重试失败项')}><IconRefresh size={16}/></button><button disabled={!batch.tasks.some(t=>t.state==='waiting'||t.state==='uploading')} onClick={()=>queue.cancel(undefined,batch.id)} aria-label={t('取消整批上传')}><IconX size={16}/></button></header>{batch.tasks.slice(0,visible[batch.id]??100).map(task=><div className={`file-upload-task ${task.state}`} key={task.id}><span className="file-upload-task-name" title={task.savedPath??task.name}>{task.directory&&<IconFolder size={16}/>}<span>{task.name}</span>{task.savedPath&&task.savedPath!==batch.directory+'/'+task.name&&<small>{task.savedPath}</small>}{task.error&&<small role="alert">{t(task.error)}</small>}</span><span>{t(labels[task.state])}{!task.directory&&<> · {uploadBytes(task.received)} / {uploadBytes(task.size)}</>}</span>{!task.directory&&<progress max={task.size||1} value={task.state==='done'&&!task.size?1:task.received}/>}<button aria-label={t(task.state==='failed'?'重试':'取消')} disabled={!['waiting','uploading','failed'].includes(task.state)} onClick={()=>task.state==='failed'?queue.retry(task.id):queue.cancel(task.id)}>{task.state==='failed'?<IconRefresh size={16}/>:<IconX size={16}/>}</button></div>)}{batch.tasks.length>(visible[batch.id]??100)&&<button onClick={()=>setVisible(v=>({...v,[batch.id]:(v[batch.id]??100)+100}))}>{t('加载更多')}</button>}</section>)}</div>
 </details>;
}
