import React,{useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {IconArrowLeft,IconArrowUp,IconFolder,IconFile,IconRefresh,IconSearch,IconX,IconCheck,IconFolderOpen,IconAdjustmentsHorizontal,IconPackage,IconFileCode,IconChevronRight} from '@tabler/icons-react';
import {t} from './i18n';
import {Switch} from './switch';
import {FolderTree} from './folder-tree';
import './file-picker.css';
type Request={id:string;accept:string[];multiple:boolean;directory:boolean;defaultPath?:string;localSelect?:(path:string)=>void};
type Entry={name:string;path:string;directory:boolean;size:number;modified?:number};
type Listing={path:string;parent:string|null;roots:{name:string;path:string}[];entries:Entry[];total:number;offset:number;skipped:number};
async function files<T>(operation:string,params:unknown,signal?:AbortSignal):Promise<T>{
 const response=await fetch(`/host/files/${operation}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(params),signal});
 if(!response.ok)throw new Error(t('服务请求失败：{0}',{0:response.status}));
 const data=await response.json();if(data.error)throw new Error(t(data.error));return data.result;
}
function extensions(accept:string[]){const mapped:Record<string,string[]>={'application/json':['.json'],'application/vnd.android.package-archive':['.apk']};return [...new Set(accept.flatMap(a=>a.split(/[;,]/)).flatMap(a=>a.startsWith('.')?[a.toLowerCase()]:mapped[a]??[]))];}
function size(bytes:number){return bytes<1024?`${bytes} B`:bytes<1048576?`${(bytes/1024).toFixed(1)} KiB`:`${(bytes/1048576).toFixed(1)} MiB`;}
// CEF announces its dialog after input.click(). Only this input opts
// into a path result; ordinary inputs and external browsers still receive Files.
let localSelection:((path:string)=>void)|undefined;
let clearLocalSelection:(()=>void)|undefined;
export function openLocalFileInput(input:HTMLInputElement,onSelect:(path:string)=>void){
 clearLocalSelection?.();localSelection=onSelect;
 const clear=()=>{if(localSelection===onSelect)localSelection=undefined;input.removeEventListener('change',clear);input.removeEventListener('cancel',clear);};
 clearLocalSelection=clear;input.addEventListener('change',clear);input.addEventListener('cancel',clear);
 input.value='';input.click();
}
export function FrameFilePicker(){
 const [request,setRequest]=useState<Request|null>(null);
 useEffect(()=>{const open=(e:Event)=>{const detail=(e as CustomEvent<Request>).detail;if(detail?.id&&Array.isArray(detail.accept)){const localSelect=localSelection;clearLocalSelection?.();clearLocalSelection=undefined;localSelection=undefined;setRequest({...detail,localSelect});}};window.addEventListener('framely.fileDialog',open);return()=>window.removeEventListener('framely.fileDialog',open);},[]);
 return request?createPortal(<FileDialog key={request.id} request={request} close={()=>setRequest(null)}/>,document.body):null;
}
function FileDialog({request,close}:{request:Request;close:()=>void}){
 const [path,setPath]=useState(()=>{try{return sessionStorage.getItem('framely.filePicker.path')??'';}catch{return '';}}),[address,setAddress]=useState(''),[query,setQuery]=useState(''),[search,setSearch]=useState(''),[hidden,setHidden]=useState(false),[onlySupported,setOnlySupported]=useState(true),[optionsOpen,setOptionsOpen]=useState(false),[offset,setOffset]=useState(0),[listing,setListing]=useState<Listing|null>(null),[selected,setSelected]=useState<Entry[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[revision,setRevision]=useState(0),[treeRevision,setTreeRevision]=useState(0);
 const initial=useRef(true),history=useRef<string[]>([]),dialog=useRef<HTMLDivElement>(null),previousFocus=useRef<HTMLElement|null>(null),done=useRef(false),completing=useRef(false),requestSequence=useRef(0),cancelRef=useRef(()=>{});
 const allowed=extensions(request.accept),supported=(entry:Entry)=>!request.directory&&(!allowed.length||allowed.some(ext=>entry.name.toLowerCase().endsWith(ext)));
 const entries=listing?.entries.filter(e=>e.directory||!onlySupported||supported(e))??[];
 async function complete(paths:string[]){if(completing.current)return;completing.current=true;setBusy(true);setError('');try{await files('complete',{id:request.id,paths:request.localSelect?[]:paths,directory:request.directory});done.current=true;if(paths.length&&listing){try{sessionStorage.setItem('framely.filePicker.path',listing.path);}catch{}}close();if(paths.length)request.localSelect?.(paths[0]);}catch(e){completing.current=false;setError(String(e));setBusy(false);}}
 cancelRef.current=()=>{void complete([]);};
 useEffect(()=>{previousFocus.current=document.activeElement as HTMLElement;const root=document.getElementById('root');const wasInert=root?.inert??false;if(root)root.inert=true;dialog.current?.querySelector<HTMLButtonElement>('button')?.focus();const key=(e:Event)=>{if(e instanceof KeyboardEvent){if(e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();cancelRef.current();}else if(e.key==='Tab'){const nodes=Array.from(dialog.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),[tabindex="0"]')??[]).filter(n=>n.getClientRects().length);if(!nodes.length)return;if(e.shiftKey&&document.activeElement===nodes[0]){e.preventDefault();nodes.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===nodes.at(-1)){e.preventDefault();nodes[0].focus();}}}else{e.stopImmediatePropagation();cancelRef.current();}};window.addEventListener('keydown',key,true);window.addEventListener('framely.back',key,true);return()=>{window.removeEventListener('keydown',key,true);window.removeEventListener('framely.back',key,true);if(root)root.inert=wasInert;previousFocus.current?.focus();if(!done.current)void files('complete',{id:request.id,paths:[]}).catch(()=>{});};},[]);
 useEffect(()=>{const timer=setTimeout(()=>{setQuery(search);setOffset(0);},180);return()=>clearTimeout(timer);},[search]);
 useEffect(()=>{const abort=new AbortController(),sequence=++requestSequence.current;setLoading(true);setError('');void files<Listing>('list',{path,query,hidden,offset,extensions:onlySupported&&!request.directory?allowed:[],directoryOnly:request.directory},abort.signal).then(data=>{if(sequence!==requestSequence.current)return;initial.current=false;setListing(data);setAddress(data.path);setSelected([]);}).catch(e=>{if(!abort.signal.aborted){if(initial.current&&path){initial.current=false;setPath('');}else setError(String(e));}}).finally(()=>{if(sequence===requestSequence.current&&!abort.signal.aborted)setLoading(false);});return()=>abort.abort();},[path,query,hidden,offset,revision,onlySupported]);
 function navigate(next:string,back=false){if(listing&&!back&&listing.path!==next)history.current.push(listing.path);setPath(next);setOffset(0);setSearch('');setQuery('');setSelected([]);setRevision(r=>r+1);}
 function choose(entry:Entry){if(entry.directory){navigate(entry.path);return;}if(!supported(entry))return;setSelected(s=>request.multiple?(s.some(e=>e.path===entry.path)?s.filter(e=>e.path!==entry.path):s.length<64?[...s,entry]:s):[entry]);}
 const canSelect=request.directory?!!listing&&!loading&&!error:!!selected.length&&!loading&&!error;
 const title=listing?.path.split('/').filter(Boolean).at(-1)??t('选择文件');
 return <div className="frame-files-backdrop" onPointerDown={e=>{if(e.target===e.currentTarget)cancelRef.current();}}><div ref={dialog} className="frame-files" role="dialog" aria-modal="true" aria-label={t(request.directory?'选择目录':'选择文件')}>
 <header><div className="frame-files-heading"><span className="frame-files-heading-icon"><IconFolderOpen size={26} stroke={1.6}/></span><div><h2>{t(request.directory?'选择目录':'选择文件')}</h2><small>{request.directory?t('浏览 Frame 上的目录'):allowed.length?`${t('支持的文件类型')} ${allowed.join(' · ')}`:t('浏览 Frame 上的文件')}</small></div></div><button className="frame-files-icon-button" aria-label={t('关闭')} disabled={busy} onClick={()=>cancelRef.current()}><IconX size={23} stroke={1.6}/></button></header>
 <div className="frame-files-body"><aside aria-label={t('文件夹树')}><p className="frame-files-sidebar-label">{t('文件夹树')}</p><FolderTree roots={listing?.roots??[]} path={listing?.path??''} hidden={hidden} refresh={treeRevision} onNavigate={navigate} read={(path,offset,hidden,signal)=>files<Listing>('list',{path,offset,hidden,directoryOnly:true},signal)}/></aside><section>
 <div className="frame-files-location"><div className="frame-files-navigation"><button className="frame-files-icon-button" aria-label={t('返回上一个目录')} disabled={busy||!history.current.length} onClick={()=>navigate(history.current.pop()!,true)}><IconArrowLeft size={22} stroke={1.7}/></button><button className="frame-files-icon-button" aria-label={t('上级目录')} disabled={busy||!listing?.parent} onClick={()=>navigate(listing!.parent!)}><IconArrowUp size={22} stroke={1.7}/></button></div><div className="frame-files-path"><IconFolder size={20} stroke={1.6}/><input aria-label={t('目录路径')} value={address} disabled={busy} onChange={e=>setAddress(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')navigate(address);}}/><button className="frame-files-go" disabled={busy||!address.trim()} onClick={()=>navigate(address)}>{t('前往')}</button></div><button className="frame-files-icon-button" aria-label={t('刷新')} disabled={busy} onClick={()=>{setRevision(r=>r+1);setTreeRevision(r=>r+1);}}><IconRefresh size={22} stroke={1.7}/></button></div>
 <div className="frame-files-toolbar"><div className="frame-files-search"><IconSearch size={22} stroke={1.6}/><input type="search" aria-label={t('搜索当前目录')} placeholder={t('搜索当前目录')} value={search} disabled={busy} onChange={e=>setSearch(e.target.value)}/></div><div className="frame-files-options-anchor"><button className={`frame-files-icon-button ${optionsOpen?'active':''}`} aria-label={t('显示选项')} aria-expanded={optionsOpen} disabled={busy} onClick={()=>setOptionsOpen(v=>!v)}><IconAdjustmentsHorizontal size={24} stroke={1.6}/></button>{optionsOpen&&<div className="frame-files-options"><label><span>{t('显示隐藏文件')}</span><Switch label={t('显示隐藏文件')} checked={hidden} disabled={busy} onChange={v=>{setOffset(0);setHidden(v);}}/></label>{!!allowed.length&&!request.directory&&<label><span>{t('仅显示支持的文件')}</span><Switch label={t('仅显示支持的文件')} checked={onlySupported} disabled={busy} onChange={v=>{setOffset(0);setOnlySupported(v);}}/></label>}</div>}</div></div>
 <div className="frame-files-directory"><h3>{title}</h3><small>{loading?t('正在读取目录…'):listing?.total===1?t('1 个项目'):t('{0} 个项目',{0:listing?.total??0})}</small></div>
 {error&&<p role="alert" className="error">{error}<button onClick={()=>setRevision(r=>r+1)} disabled={busy}>{t('重试')}</button></p>}
 <div className="frame-files-columns" aria-hidden="true"><span>{t('名称')}</span><span>{t('文件大小')}</span><span>{t('修改时间')}</span><span/></div>
 <div className="frame-files-list" aria-busy={loading}>{loading?<div className="frame-files-loading" role="status"><IconRefresh size={28}/><p>{t('正在读取目录…')}</p></div>:entries.map(entry=>{const active=selected.some(s=>s.path===entry.path),extension=entry.name.toLowerCase().split('.').at(-1),FileIcon=entry.directory?IconFolder:extension==='apk'?IconPackage:extension==='json'?IconFileCode:IconFile;return <button key={entry.path} title={entry.name} className={`frame-file-row ${active?'selected':''}`} aria-pressed={!entry.directory?active:undefined} disabled={busy||(!entry.directory&&!supported(entry))} onClick={()=>{setOptionsOpen(false);choose(entry);}} onDoubleClick={()=>{if(!entry.directory&&supported(entry))void complete([entry.path]);}}><span className={`frame-file-symbol ${entry.directory?'folder':extension==='apk'?'apk':''}`}><FileIcon size={28} stroke={1.55}/></span><span className="frame-file-name"><b>{entry.name}</b><small>{entry.directory?t('文件夹'):extension==='apk'?'APK':extension?.toUpperCase()}</small></span><span className="frame-file-size">{entry.directory?'':size(entry.size)}</span><span className="frame-file-modified">{entry.modified?new Date(entry.modified*1000).toLocaleDateString(document.documentElement.lang||undefined):''}</span><span className="frame-file-check">{entry.directory?<IconChevronRight size={19} stroke={1.6}/>:active?<IconCheck size={21} stroke={2}/>:null}</span></button>})}{!loading&&!entries.length&&!error&&<div className="frame-files-empty"><IconSearch size={36} stroke={1.4}/><p className="empty">{t('当前目录没有匹配的文件')}</p></div>}</div>
 {!!listing&&listing.total>200&&<div className="frame-files-pages"><button disabled={busy||loading||offset===0} onClick={()=>setOffset(v=>Math.max(0,v-200))}>{t('上一页')}</button><span>{offset+1}-{Math.min(offset+200,listing.total)} / {listing.total}</span><button disabled={busy||loading||offset+200>=listing.total} onClick={()=>setOffset(v=>v+200)}>{t('下一页')}</button></div>}
 {!!listing?.skipped&&<small>{t('部分项目无法访问，已跳过。')}</small>}
 </section></div><footer><div className={`frame-files-selection ${canSelect?'has-selection':''}`}><span className="frame-files-selection-icon">{canSelect?<IconCheck size={22}/>:<IconFile size={22} stroke={1.5}/>}</span><span>{request.directory?listing?.path:selected.length===1?selected[0].name:selected.length?t('已选择 {0} 个文件',{0:selected.length}):t('请选择要导入的文件')}{selected.length===1&&<small>{size(selected[0].size)}</small>}</span></div><button className="frame-files-cancel" disabled={busy} onClick={()=>cancelRef.current()}>{t('取消')}</button><button className="frame-files-confirm" disabled={busy||!canSelect} onClick={()=>void complete(request.directory?[listing!.path]:selected.map(e=>e.path))}>{busy?t('正在处理…'):t('选择')}</button></footer>
 </div></div>;
}
