import React,{useEffect,useId,useRef,useState} from 'react';
import {IconUpload,IconX,IconRefresh,IconFolder} from '@tabler/icons-react';
import {FileUploadQueue,uploadBatchFileCounts} from './file-upload-queue';
import {Select} from './localized-select';
import {t} from './i18n';
export const uploadBytes=(n:number)=>n<1024?`${n} B`:n<1024**2?`${(n/1024).toFixed(1)} KiB`:n<1024**3?`${(n/1024**2).toFixed(1)} MiB`:`${(n/1024**3).toFixed(1)} GiB`;
const labels={waiting:'等待上传',uploading:'正在上传',done:'已完成',skipped:'已跳过',failed:'上传失败',cancelled:'已取消'};
export function FileUploadPanel({queue,limit,onLimit,active=true}:{queue:FileUploadQueue;limit:number;onLimit:(n:number)=>void;active?:boolean}){
 const [open,setOpen]=useState(false),panelId=useId(),anchor=useRef<HTMLDivElement>(null),trigger=useRef<HTMLButtonElement>(null);
 useEffect(()=>{if(!active)setOpen(false);},[active]);
 useEffect(()=>{if(!open)return;const outside=(e:PointerEvent)=>{if(!anchor.current?.contains(e.target as Node))setOpen(false);};const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();setOpen(false);trigger.current?.focus();}};document.addEventListener('pointerdown',outside);document.addEventListener('keydown',key,true);return()=>{document.removeEventListener('pointerdown',outside);document.removeEventListener('keydown',key,true);};},[open]);
 const [visible,setVisible]=useState<Record<string,number>>({});
 const tasks=queue.batches.flatMap(b=>b.tasks),pending=tasks.filter(t=>t.state==='waiting'||t.state==='uploading').length;
 return <div className="file-upload-queue" ref={anchor} data-file-drop-block><button ref={trigger} className={`file-upload-toggle ${open?'active':''}`} aria-expanded={open} aria-controls={panelId} onClick={()=>setOpen(v=>!v)}><IconUpload size={18}/>{t('上传任务队列')}{pending>0&&<span className="file-upload-badge">{pending}</span>}</button>
 {open&&<div id={panelId} className="file-upload-popover" role="dialog" aria-label={t('上传任务队列')}><div className="file-upload-heading"><strong>{t('上传任务队列')}</strong><span>{t('{0} 项进行中 · 共 {1} 项',{0:pending,1:tasks.length})}</span><button aria-label={t('关闭')} onClick={()=>{setOpen(false);trigger.current?.focus();}}><IconX size={18}/></button></div><div className="file-upload-controls"><div className="file-upload-limit"><span>{t('同时上传文件数')}</span><Select label={t('同时上传文件数')} value={String(limit)} onChange={n=>onLimit(Number(n))} options={Array.from({length:8},(_,i)=>({value:String(i+1),label:String(i+1)}))}/></div><button onClick={()=>queue.clear()}>{t('清除已结束记录')}</button></div>
 <div className="file-upload-batches">{queue.batches.map(batch=>{const count=uploadBatchFileCounts(batch);return <section key={batch.id}><header><span title={batch.directory}>{batch.directory}</span><button disabled={!batch.tasks.some(t=>t.state==='failed')} onClick={()=>queue.retry(undefined,batch.id)} aria-label={t('重试失败项')}><IconRefresh size={16}/></button><button disabled={!batch.tasks.some(t=>t.state==='waiting'||t.state==='uploading')} onClick={()=>queue.cancel(undefined,batch.id)} aria-label={t('取消整批上传')}><IconX size={16}/></button></header><div className="file-upload-batch-count" role="status">{t('已上传 {0} / {1} 个文件',{0:count.uploaded,1:count.total})}</div>{batch.tasks.slice(0,visible[batch.id]??100).map(task=><div className={`file-upload-task ${task.state}`} key={task.id}><span className="file-upload-task-name" title={task.savedPath??task.name}>{task.directory&&<IconFolder size={16}/>}<span>{task.name}</span>{task.savedPath&&task.savedPath!==batch.directory+'/'+task.name&&<small>{task.savedPath}</small>}{task.error&&<small role="alert">{t(task.error)}</small>}</span><span>{t(labels[task.state])}{!task.directory&&<> · {uploadBytes(task.received)} / {uploadBytes(task.size)}</>}</span>{!task.directory&&<progress max={task.size||1} value={task.state==='done'&&!task.size?1:task.received}/>}<button aria-label={t(task.state==='failed'?'重试':'取消')} disabled={!['waiting','uploading','failed'].includes(task.state)} onClick={()=>task.state==='failed'?queue.retry(task.id):queue.cancel(task.id)}>{task.state==='failed'?<IconRefresh size={16}/>:<IconX size={16}/>}</button></div>)}{batch.tasks.length>(visible[batch.id]??100)&&<button onClick={()=>setVisible(v=>({...v,[batch.id]:(v[batch.id]??100)+100}))}>{t('加载更多')}</button>}</section>;})}{!queue.batches.length&&<p className="file-upload-empty">{t('暂无上传任务')}</p>}</div>
 </div>}</div>;
}
