import React,{useEffect,useMemo,useRef,useState} from 'react';
import {IconChevronRight,IconFolder,IconFolderOpen,IconHome,IconDeviceSdCard,IconRefresh} from '@tabler/icons-react';
import {t} from './i18n';
type Folder={name:string;path:string;directory:boolean};
type Page={entries:Folder[];total:number};
type NodeState={children:Folder[];total:number;loading:boolean;error?:string;loaded:boolean};
type Root={name:string;path:string};
export function FolderTree({roots,path,hidden,refresh,onNavigate,read}:{roots:Root[];path:string;hidden:boolean;refresh:number;onNavigate:(path:string)=>void;read:(path:string,offset:number,hidden:boolean,signal:AbortSignal)=>Promise<Page>}){
 const rootKey=JSON.stringify(roots),topRoots=useMemo(()=>roots.filter((root,index)=>!roots.some((other,j)=>other.path===root.path?j<index:root.path.startsWith(other.path+'/'))),[rootKey]);
 const [nodes,setNodes]=useState<Record<string,NodeState>>({}),[expanded,setExpanded]=useState<Set<string>>(new Set());
 const cache=useRef<Record<string,NodeState>>({}),requests=useRef(new Map<string,AbortController>()),reader=useRef(read),generation=useRef(0);reader.current=read;
 const update=(key:string,value:NodeState)=>{cache.current={...cache.current,[key]:value};setNodes(cache.current);};
 async function load(key:string,more=false){const previous=cache.current[key];if(previous?.loading||previous?.loaded&&!more&&!previous.error)return;const controller=new AbortController();requests.current.set(key,controller);const currentGeneration=generation.current,children=more?previous?.children??[]:[];update(key,{children,total:previous?.total??0,loading:true,loaded:previous?.loaded??false});try{const result=await reader.current(key,children.length,hidden,controller.signal);if(controller.signal.aborted||generation.current!==currentGeneration)return;const existing=new Set(children.map(c=>c.path));update(key,{children:[...children,...result.entries.filter(e=>e.directory&&!existing.has(e.path))],total:result.total,loading:false,loaded:true});}catch(e){if(!controller.signal.aborted&&generation.current===currentGeneration)update(key,{children,total:previous?.total??0,loading:false,loaded:false,error:String(e)});}finally{if(requests.current.get(key)===controller)requests.current.delete(key);}}
 useEffect(()=>{generation.current++;for(const controller of requests.current.values())controller.abort();requests.current.clear();cache.current={};setNodes({});},[hidden,rootKey,refresh]);
 useEffect(()=>{const root=topRoots.find(root=>path===root.path||path.startsWith(root.path+'/'));if(!root)return;const ancestors=[root.path];let next=root.path;for(const segment of path.slice(root.path.length).split('/').filter(Boolean)){next+='/'+segment;ancestors.push(next);}setExpanded(current=>new Set([...current,...ancestors]));for(const ancestor of new Set([...expanded,...ancestors])){if(topRoots.some(root=>ancestor===root.path||ancestor.startsWith(root.path+'/')))void load(ancestor);}},[path,hidden,rootKey,refresh]);
 useEffect(()=>()=>{generation.current++;for(const controller of requests.current.values())controller.abort();},[]);
 function toggle(key:string){const open=!expanded.has(key);setExpanded(current=>{const next=new Set(current);if(open)next.add(key);else next.delete(key);return next;});if(open)void load(key);}
 function branch(folder:Root,depth:number):React.ReactNode{const label=depth===0?t(folder.name):folder.name,state=nodes[folder.path],open=expanded.has(folder.path),selected=folder.path===path,hasChildren=!state?.loaded||!!state.children.length||path.startsWith(folder.path+'/'),FolderIcon=depth===0?(folder.name==='主目录'?IconHome:folder.path.startsWith('/run/media/')?IconDeviceSdCard:IconFolder):open?IconFolderOpen:IconFolder;
 const children=[...(state?.children??[])];if(path.startsWith(folder.path+'/')){const name=path.slice(folder.path.length+1).split('/')[0],childPath=folder.path+'/'+name;if(!children.some(child=>child.path===childPath))children.push({name,path:childPath,directory:true});}
 return <div key={folder.path} role="treeitem" aria-label={label} aria-selected={selected} aria-expanded={hasChildren?open:undefined} aria-level={depth+1}><div className={`frame-folder-row ${selected?'active':''}`} style={{paddingLeft:8+depth*18}}><button className="frame-folder-toggle" aria-label={t(open?'收起 {0}':'展开 {0}',{0:label})} disabled={!hasChildren} onClick={()=>toggle(folder.path)}><IconChevronRight size={17} stroke={1.8} style={{transform:open?'rotate(90deg)':'none',visibility:hasChildren?'visible':'hidden'}}/></button><button className="frame-folder-name" title={label} onClick={()=>onNavigate(folder.path)}><FolderIcon size={21} stroke={1.6}/><span>{label}</span></button></div>{open&&<div role="group">{state?.loading&&!state.children.length&&<div className="frame-folder-status" style={{paddingLeft:30+depth*18}}><IconRefresh size={16}/><span>{t('正在读取')}</span></div>}{children.map(child=>branch(child,depth+1))}{state?.error&&<button className="frame-folder-retry" title={state.error} onClick={()=>void load(folder.path)}>{t('无法读取目录')} · {t('重试')}</button>}{state?.loaded&&state.children.length<state.total&&<button className="frame-folder-more" disabled={state.loading} onClick={()=>void load(folder.path,true)}>{state.loading?t('正在读取'):t('加载更多目录')}</button>}</div>}</div>;
 }
 return <div className="frame-folder-tree" role="tree" aria-label={t('文件夹树')}>{topRoots.map(root=>branch(root,0))}</div>;
}
