import {NotificationSettings,PopupPermission,useReadInbox,defaultNotificationConfig,type NotificationConfig} from './notification-settings';
import {NotificationCenter,type NotificationEntry} from './notifications';
import {IconBell} from '@tabler/icons-react';
import {t} from './i18n';
import {uploadFile} from './upload';
import {LanguageSettings} from './language';
import {configureLanguage,currentLanguage,LanguagePack} from './i18n';
import {AgreementGate,AgreementState} from './agreement';
import {ProxySettings,ProxyConfig} from './proxy';
import {NetworkSettings,NetworkPanel} from './network';
import {Subscriptions,Subscription} from './subscriptions';
import {RelationsInfo} from './relations';
import {InstallReview} from './install-review';
import {MemoryLimit} from './memory-limit';
import {installScrollbars} from '../../sdk/src/scrollbars';
installScrollbars();
import React,{useEffect,useRef,useState} from 'react';import{createRoot}from'react-dom/client';import{uploadChunk,api,viewKey}from'./api';import {Icon,Brand} from './icons';import {Store,Sources,PluginImage,PluginLinks,PluginAuthor,installedIcon,runJob,Transfer,Job,Presentation,compareVersions} from './store';import {SystemUpdates} from './updates';import './style.css';if(location.pathname==='/notifications')document.documentElement.classList.add('notification-view');
type Manifest=Presentation&{id:string;name:string;version:string;author:string;description:string;backend?:{runAs:string;autostart:boolean;memoryLimitMiB?:number};lifecycle?:{runAs?:string};dependencies?:Record<string,unknown>;optionalDependencies?:Record<string,unknown>;conflicts?:Record<string,string>;exclusiveResources?:string[];ui:{quickPage?:string;windows:Record<string,unknown>}};
type Plugin={manifest:Manifest;enabled:boolean;favorite:boolean;order:number;source?:string;error?:string};
type Source={id:string;name:string;url:string;enabled:boolean;allowHttp:boolean};
type Status={agreement?:AgreementState;version:string;build?:string;systemUpdate?:any;previousRelease?:string;database:{notificationSettings?:NotificationConfig;language?:string;proxy?:ProxyConfig;networkPanel?:NetworkPanel;plugins:Record<string,Plugin>;sources:Source[];subscriptions?:Subscription[];sourceOrigins?:Record<string,{manual:boolean;subscriptions:Record<string,string>}>;safeMode:boolean;updateSource?:{url:string}|null;updateChannel?:'stable'|'testing'};notifications:NotificationEntry[];inbox?:NotificationEntry[];notificationBadge?:number;runtime?:Record<string,{phase:string;detail:any}>;running:string[]};
const managerMode=location.pathname==='/manager';
const empty:Status={version:'0.4.0',database:{plugins:{},sources:[],safeMode:false},notifications:[],running:[]};

let pluginLanguagePreference='auto';
function PluginFrame({plugin,entry='quick'}:{plugin:string;entry?:string}){
 const ref=useRef<HTMLIFrameElement>(null);
 const [error,setError]=useState(''),[source,setSource]=useState<string|null>(null),[sandbox,setSandbox]=useState('allow-scripts');
 const [attempt,setAttempt]=useState(0);
 useEffect(()=>{
  let live=true;setError('');setSource(null);
  const methods:Record<string,string>={call:'plugin.call',dependencies:'plugin.dependencies','window.open':'window.open','window.close':'window.close','notification.send':'notification.send','notification.remove':'notification.remove','notification.dismiss':'notification.dismiss'};
  async function message(e:MessageEvent){
   if(e.source!==ref.current?.contentWindow||e.data?.channel!=='framely.plugin')return;
   const {id,op,params}=e.data;if(!Number.isSafeInteger(id)||typeof op!=='string')return;
   try{let result;
    if(op==='language.get')result={preference:pluginLanguagePreference,language:currentLanguage()};
    else if(op==='ui.close'){
     const view=viewKey();
     if(view==='menu')result=await api('host.menu.close');
     else if(view==='framely.manager')result=await api('host.manager.close');
     else result=await api('window.close',{plugin,window:entry});
    }
    else if(op==='ui.visibility.get')result=await api('ui.visibility.get',{view:viewKey()});
    else if(op==='haptic')result=await api('host.haptic',{view:viewKey()});
    else if(op==='keyboard')result=await api('host.keyboard',{...params,view:viewKey()});
    else{const method=methods[op];if(!method)throw new Error(t('插件请求不支持的能力'));result=await api(method,{...params,plugin});}
    if(live)ref.current?.contentWindow?.postMessage({channel:'framely.reply',id,result},'*');
   }catch(e){if(live)ref.current?.contentWindow?.postMessage({channel:'framely.reply',id,error:String(e)},'*');}
  }
  const event=(e:Event)=>{const value=(e as CustomEvent).detail;if(value.kind==='ui.visibility.changed'){api('ui.visibility.get',{view:viewKey()}).then(data=>{if(live)ref.current?.contentWindow?.postMessage({channel:'framely.reply',event:{type:'ui.visibility.changed',data}},'*');}).catch(()=>{});}if(value.kind==='plugin.dependency.changed')ref.current?.contentWindow?.postMessage({channel:'framely.reply',event:{type:'dependencies.changed'}},'*');if(value.plugin===plugin&&value.kind==='plugin.event')ref.current?.contentWindow?.postMessage({channel:'framely.reply',event:{type:value.event,data:value.data}},'*');};
  const language=()=>ref.current?.contentWindow?.postMessage({channel:'framely.reply',event:{type:'language.changed',data:{preference:pluginLanguagePreference,language:currentLanguage()}}},'*');
  window.addEventListener('framely.event',event);window.addEventListener('framely.language',language);window.addEventListener('message',message);
  void (async()=>{
   await api('plugin.open',{plugin});const status=await api('status');
   const local=!!(status.database.plugins[plugin]?.manifest.ui.windows[entry] as any)?.localWeb;
   let url=`/plugin-frame/${plugin}/${entry}`,flags=local?'allow-scripts allow-downloads':'allow-scripts';
   if(local&&entry!=='quick'){
    if(!['localhost','127.0.0.1','[::1]'].includes(location.hostname))throw new Error('Open this window on the Frame device');
    const value=await api('plugin.call',{plugin,method:'window.get',params:{window:entry}});
    const target=new URL(value.url);
    if(target.protocol!=='http:'||target.hostname!=='localhost'||!target.port||target.port===location.port||target.username||target.password||target.pathname!==`/framely-window/${entry}`||target.search||target.hash)throw new Error('Invalid local plugin window URL');
    url=target.href;flags='allow-scripts allow-same-origin allow-forms allow-downloads allow-popups allow-popups-to-escape-sandbox';
   }
   if(live){setSandbox(flags);setSource(url);}
  })().catch(e=>{if(live)setError(String(e));});
  return()=>{live=false;window.removeEventListener('message',message);window.removeEventListener('framely.event',event);window.removeEventListener('framely.language',language);};
 },[plugin,entry,attempt]);
 return error?<div><p className="error">{error}</p><button onClick={()=>setAttempt(v=>v+1)}>{t('重试')}</button></div>:source?<iframe title={t('插件页面')} ref={ref} sandbox={sandbox} src={source} allow="clipboard-read; clipboard-write; fullscreen"/>:<p>{t('正在加载…')}</p>;
}
function App(){
 const[catalogTarget,setCatalogTarget]=useState<{plugin:string;source?:string}|null>(null);const runtimeLabels:Record<string,string>={starting:t("初始化中"),running:t("运行中"),stopping:t("停止中"),stopped:t("已停止"),recovering:t("等待恢复"),failed:t("失败"),crashed:t("异常退出"),ready:t("已就绪"),installed:t("已安装"),'waiting-dependency':t("等待依赖")};const [status,setStatus]=useState<Status>(empty),[error,setError]=useState(''),[tab,setTab]=useState(managerMode?(location.hash==='#catalog'?'catalog':location.hash==='#updates'?'about':location.hash==='#notification-settings'?'notification-settings':'installed'):'favorites'),[page,setPage]=useState<string|null>(null),[busy,setBusy]=useState(false),[query,setQuery]=useState(''),[manage,setManage]=useState<Plugin|null>(null),[install,setInstall]=useState<any>(null),[confirmRunAs,setConfirmRunAs]=useState(false),[logs,setLogs]=useState<string|null>(null),[importing,setImporting]=useState(false),[transfer,setTransfer]=useState<Job|null>(null),[downloadRequest,setDownloadRequest]=useState<any>(null),[relationAction,setRelationAction]=useState<any>(null),[reviewAgreement,setReviewAgreement]=useState(false),[agreementDeclined,setAgreementDeclined]=useState(false),[languageFiles,setLanguageFiles]=useState<string[]>([]);
 useEffect(()=>{const ticket=install?.ticket;return()=>{if(ticket)void api('job.cancel',{job:ticket}).catch(()=>{});};},[install?.ticket]);
 const localePacks=useRef<LanguagePack[]|null>(null);const localePreference=useRef<string|null>(null);
 const readError=useReadInbox(!managerMode&&tab==='notifications'&&!page&&!!status.agreement?.accepted,status.inbox??[],refresh);
 async function refreshLanguages(){const v=await api('language.list');localePacks.current=v.packs??[];setLanguageFiles(v.invalidFiles??[]);await refresh();}

 useEffect(()=>{
  const panel=Array.from(document.querySelectorAll<HTMLElement>('.modal')).at(-1);if(!panel)return;
  const previous=document.activeElement as HTMLElement|null;
  const items=()=>Array.from(panel.querySelectorAll<HTMLElement>('a[href]:not([aria-disabled="true"]),button:not(:disabled),input:not(:disabled),textarea,summary,[tabindex="0"]')).filter(el=>el.getClientRects().length);
  items()[0]?.focus();
  const key=(event:KeyboardEvent)=>{if(event.key!=='Tab')return;const list=items(),first=list[0],last=list.at(-1);if(event.shiftKey&&(document.activeElement===first||!panel.contains(document.activeElement))){event.preventDefault();last?.focus();}else if(!event.shiftKey&&(document.activeElement===last||!panel.contains(document.activeElement))){event.preventDefault();first?.focus();}};
  document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);previous?.focus();};
 },[manage,install,logs,importing,transfer?.id,relationAction]);
 async function refresh(){try{const s=await api<Status>('status');if(localePacks.current===null||localePreference.current!==(s.database.language??'auto')){const v=await api('language.list');localePacks.current=v.packs??[];setLanguageFiles(v.invalidFiles??[]);}const previousLanguage=currentLanguage(),previousPreference=pluginLanguagePreference;configureLanguage(s.database.language??'auto',localePacks.current??[]);pluginLanguagePreference=s.database.language??'auto';if(previousLanguage!==currentLanguage()||previousPreference!==pluginLanguagePreference)window.dispatchEvent(new Event('framely.language'));localePreference.current=s.database.language??'auto';setStatus(s);}catch(e){setError(String(e));}}
 useEffect(()=>{void refresh();const t=setInterval(()=>void refresh(),1000);return()=>clearInterval(t);},[]);
 useEffect(()=>{let live=true,cursor=0;const t=setInterval(()=>{api('ui.events',{cursor}).then(v=>{if(live){cursor=v.cursor;for(const e of v.events)window.dispatchEvent(new CustomEvent('framely.event',{detail:e}));}}).catch(()=>{});},1000);return()=>{live=false;clearInterval(t);};},[]);
 useEffect(()=>{const back=(e:Event)=>{if(e instanceof KeyboardEvent&&e.key!=='Escape')return;if(transfer){if(['done','failed','cancelled'].includes(transfer.phase))setTransfer(null);}else if(relationAction)setRelationAction(null);else if(importing)setImporting(false);else if(logs!==null)setLogs(null);else if(manage)setManage(null);else if(install)setInstall(null);else if(page)setPage(null);else if(!managerMode)void api('host.menu.close');};window.addEventListener('framely.back',back);window.addEventListener('keydown',back);return()=>{window.removeEventListener('framely.back',back);window.removeEventListener('keydown',back);};},[manage,install,logs,page,importing,transfer,relationAction]);
 async function action(f:()=>Promise<unknown>){setBusy(true);setError('');try{await f();await refresh();}catch(e){setError(String(e));await refresh();}finally{setBusy(false);}}
 async function inspect(request:any){setBusy(true);setDownloadRequest(request.upload?null:request);setError('');try{const v=await runJob('inspect.start',request,setTransfer);setInstall({ticket:v.job,info:v.result});setTransfer(null);setConfirmRunAs(false);}catch(e){setTransfer(v=>v?{...v,phase:v.phase==='cancelled'?'cancelled':'failed',error:String(e)}:null);setError(String(e));}finally{setBusy(false);}}
 async function resolveChoice(id:string,url:string){setBusy(true);try{const v=await runJob('inspect.resolve.start',{ticket:install.ticket,dependencySources:{[id]:url}},setTransfer);setInstall({ticket:v.job,info:v.result});setTransfer(null);}catch(e){setError(String(e));}finally{setBusy(false);}}
 async function changePlugin(plugin:Plugin,kind:'enable'|'uninstall',extra:any={}){
  const id=plugin.manifest.id;
  if(kind==='enable'&&!plugin.enabled){const plan=await api('plugin.enable.preview',{plugin:id});const others=plan.enable.filter((target:string)=>target!==id&&!status.database.plugins[target]?.enabled);if(others.length||plan.disable.length){setRelationAction({title:t("确认启用计划"),enable:plan.enable,disable:plan.disable,method:'plugin.enable',params:{plugin:id,enabled:true,approve:true,fingerprint:plan.fingerprint}});return;}await api('plugin.enable',{plugin:id,enabled:true});}
  else{const plan=await api('plugin.disable.preview',{plugin:id});if(plan.dependents.length){setRelationAction({title:kind==='uninstall'?t("确认卸载及依赖停用"):t("确认停用计划"),enable:[],disable:plan.dependents,method:kind==='uninstall'?'plugin.uninstall':'plugin.enable',params:{plugin:id,enabled:false,purge:false,...extra,approveDependents:true,fingerprint:plan.fingerprint}});return;}await api(kind==='uninstall'?'plugin.uninstall':'plugin.enable',{plugin:id,enabled:false,purge:false,...extra});}
  setManage(null);
 }
 useEffect(()=>{if(!managerMode)return;const navigate=()=>{if(['#catalog','#updates','#notification-settings'].includes(location.hash)){setPage(null);setCatalogTarget(null);setTab(location.hash==='#updates'?'about':location.hash==='#notification-settings'?'notification-settings':'catalog');}};window.addEventListener('hashchange',navigate);return()=>window.removeEventListener('hashchange',navigate);},[]);
 async function loadCatalog(){setCatalogTarget(null);setTab('catalog');}
 const plugins=Object.values(status.database.plugins).sort((a,b)=>a.order-b.order);
 const listedPlugins=plugins.filter(p=>(tab==='installed'||p.favorite)&&(managerMode||tab!=='installed'||p.enabled)&&`${p.manifest.name} ${p.manifest.description}`.toLowerCase().includes(query.toLowerCase()));
 const onlyDisabledInstalled=!managerMode&&tab==='installed'&&plugins.length>0&&listedPlugins.length===0&&!query;
 const selected=page?status.database.plugins[page]:null;
 const installedVersion=install?.info.installedVersion;
 const installDifference=installedVersion?compareVersions(install.info.manifest.version,installedVersion):null;
 const installTitle=install?(installedVersion?(installDifference===0?t("重新安装 {0}",{0:install.info.manifest.name}):installDifference!==null&&installDifference<0?t("降级 {0}",{0:install.info.manifest.name}):t("更新 {0}",{0:install.info.manifest.name})):t("安装 {0}",{0:install.info.manifest.name})):'';
 const parts=location.pathname.split('/');const windowPlugin=parts[1]==='window'?parts[2]:null;
 function move(p:Plugin,delta:number){const ids=plugins.map(p=>p.manifest.id);const from=ids.indexOf(p.manifest.id),to=from+delta;if(to<0||to>=ids.length)return;[ids[from],ids[to]]=[ids[to],ids[from]];void action(()=>api('plugin.order',{plugins:ids}));}
 if(!status.agreement)return parts[1]==='notifications'?null:<div className="app"><p className="empty">{error||t("正在连接 Framely…")}</p></div>;
 if(parts[1]==='notifications'&&!status.agreement.accepted)return null;
 if(!status.agreement.accepted)return <AgreementGate language={{value:status.database.language??'auto',packs:localePacks.current??[]}} key="required" initialDeclined={agreementDeclined} agreement={status.agreement} refresh={refresh}/>;
 if(reviewAgreement)return <AgreementGate language={{value:status.database.language??'auto',packs:localePacks.current??[]}} key="review" agreement={status.agreement} refresh={refresh} onClose={()=>setReviewAgreement(false)} onRevoked={closed=>{setAgreementDeclined(!closed);setReviewAgreement(false);setPage(null);setManage(null);}}/>;
 if(parts[1]==='notifications')return <NotificationCenter items={status.notifications} plugins={status.database.plugins} safeMode={status.database.safeMode} refresh={refresh}/>;
 if(windowPlugin){const p=status.database.plugins[windowPlugin];return <div className="app plugin-window">{p?.enabled&&!status.database.safeMode?<PluginFrame plugin={windowPlugin} entry={parts[3]}/>:<div className="empty"><p>{t("插件已停用或正在启动。")}</p><button onClick={()=>void action(()=>api('window.close',{plugin:windowPlugin,window:parts[3]}))}>{t("关闭")}</button></div>}{error&&<p className="error">{error}</p>}</div>;}
 return <div className={`app ${managerMode?'manager':'quick'}`}><header className="shell-header"><strong className="brand-title"><Brand wordmark/></strong>{managerMode?<><button className="primary" onClick={()=>setImporting(true)}><Icon name="download"/>{t("安装插件")}</button><button className="icon-button" aria-label={t("关闭管理窗口")} onClick={()=>void api('host.manager.close')}><Icon name="close"/></button></>:<><button className="icon-button quick-library-button" aria-label={t("插件库")} onClick={()=>void action(()=>api('host.manager.open',{page:'catalog'}))}><Icon name="store"/><span>{t("插件库")}</span></button><button className="icon-button" aria-label={t("关闭菜单")} onClick={()=>void api('host.menu.close')}><Icon name="close"/></button></>}</header>{error&&<p className="error" role="alert">{error}<button onClick={()=>setError('')}>×</button></p>}{status.database.safeMode&&<p className="banner">{t("安全模式：第三方插件暂停运行。")}</p>}
 {selected?<><div className="page-title"><button onClick={()=>setPage(null)}>{t("‹ 返回")}</button><strong>{selected.manifest.name}</strong><button onClick={()=>void action(()=>api('plugin.favorite',{plugin:page,favorite:!selected.favorite}))}>{selected.favorite?'★':'☆'}</button>{managerMode&&<button onClick={()=>setManage(selected)}>{t("管理")}</button>}</div>{selected.enabled&&!status.database.safeMode&&selected.manifest.ui.quickPage?<PluginFrame plugin={page!}/>:<p className="empty">{t("插件已停用、处于安全模式或没有快捷页面。")}</p>}</>:<div className="workspace"><nav aria-label={t("主导航")}>{(managerMode?[['installed',t("已安装"),'plugins'],['catalog',t("插件库"),'download'],['sources',t("插件源导航"),'link'],['settings',t("设置"),'settings'],['notification-settings',t("通知设置导航"),'bell'],['about',t("关于"),'info']]:[['favorites',t("常用"),'star'],['installed',t("已安装"),'plugins'],['notifications',t("通知"),'bell'],['settings',t("设置"),'settings']]).map(([key,label,icon])=><button className={tab===key?'active':''} aria-current={tab===key?'page':undefined} key={key} onClick={()=>key==='catalog'?void loadCatalog():setTab(key)}>{icon==='bell'?<IconBell size={24} stroke={1.8}/>:<Icon name={icon as any}/>}<span>{label}{key==='notifications'&&!!status.notificationBadge&&<small className="notification-count">{status.notificationBadge!>99?'99+':status.notificationBadge}</small>}</span></button>)}{managerMode&&<div className="nav-foot"><span>{plugins.length}{t("个已安装插件")}</span><small>{status.version}</small></div>}</nav><main className="content">
 {(tab==='favorites'||tab==='installed')&&<>
 {managerMode&&<div className="list-heading"><div><h1>{t("已安装")}</h1><p>{plugins.length}{t("个插件，")}{plugins.filter(p=>p.enabled).length}{t("个已启用")}</p></div><div className="search-field"><Icon name="search"/><input aria-label={t("搜索已安装插件")} placeholder={t("搜索插件")} value={query} onChange={e=>setQuery(e.target.value)}/></div></div>}
 {managerMode&&<div className="list-columns"><span>{t("插件")}</span><span>{t("状态")}</span><span>{t("版本")}</span><span>{t("操作")}</span></div>}<div className="plugin-list">{listedPlugins.map(p=><article className={`plugin-row ${!p.enabled?'disabled':''}`} key={p.manifest.id}>
 <button className="plugin-main" onClick={()=>setPage(p.manifest.id)}><PluginImage src={installedIcon(p)} name={p.manifest.name} size={48}/><span className="plugin-copy"><b>{p.manifest.name}</b>{managerMode&&<small>{p.manifest.description}</small>}<span className="plugin-meta"><i className={`status-dot ${p.error?'failed':!p.enabled?'off':''}`}/>{p.error?t("异常"):!p.enabled?t("已停用"):runtimeLabels[status.runtime?.[p.manifest.id]?.phase??'']??(status.running.includes(p.manifest.id)?t("运行中"):t("已启用"))}{!managerMode&&<span className="version">{p.manifest.version}</span>}</span></span></button>
 {managerMode&&<><span className="row-state">{p.error?t("异常"):!p.enabled?t("已停用"):runtimeLabels[status.runtime?.[p.manifest.id]?.phase??'']??(status.running.includes(p.manifest.id)?t("运行中"):t("已启用"))}</span><span className="row-version">{p.manifest.version}</span><button className={`plugin-switch ${p.enabled?'on':''}`} role="switch" aria-checked={p.enabled} aria-label={t("启用 {0}", {"0": p.manifest.name})} disabled={busy} onClick={()=>void action(()=>changePlugin(p,'enable'))}><span/></button></>}<button className={`icon-button favorite ${p.favorite?'selected':''}`} aria-label={t("收藏 {0}", {"0": p.manifest.name})} onClick={()=>void action(()=>api('plugin.favorite',{plugin:p.manifest.id,favorite:!p.favorite}))}><Icon name="star" size={23} filled={p.favorite}/></button>
 {managerMode&&<button className="icon-button" aria-label={t("管理 {0}", {"0": p.manifest.name})} onClick={()=>setManage(p)}><Icon name="more"/></button>}
 </article>)}</div>
 {listedPlugins.length===0&&<div className="empty-state"><span className="empty-symbol"><Icon name={tab==='favorites'?'star':'plugins'} size={46}/></span><h2>{query?t("未找到插件"):tab==='favorites'?t("没有收藏的插件"):onlyDisabledInstalled?t("没有已启用的插件"):t("还没有安装插件")}</h2><p>{query?t("换一个关键词再试。"):tab==='favorites'?t("点击插件旁的星标，将它加入常用。"):onlyDisabledInstalled?t("打开插件管理以启用插件。"):t("打开插件管理以安装插件。")}</p><button className="primary" onClick={()=>query?setQuery(''):tab==='favorites'?setTab('installed'):managerMode?setImporting(true):void api('host.manager.open')}>{query?t("清除搜索"):tab==='favorites'?t("查看已安装"):managerMode?t("安装插件"):t("打开插件管理")}</button></div>}
 </>}
 {tab==='notifications'&&!managerMode&&<><NotificationCenter inbox items={status.inbox??[]} plugins={status.database.plugins} safeMode={status.database.safeMode} refresh={refresh} controls={<PopupPermission config={status.database.notificationSettings??defaultNotificationConfig} refresh={refresh}/>}/>{readError&&<p className="error" role="alert">{readError}</p>}</>}
 {tab==='notification-settings'&&managerMode&&<NotificationSettings config={status.database.notificationSettings??defaultNotificationConfig} plugins={status.database.plugins} refresh={refresh}/>}
 {tab==='sources'&&managerMode&&<><div className="list-heading"><div><h1>{t("插件源")}</h1><p>{t("管理插件目录及订阅。")}</p></div></div><section className="settings-card"><Sources origins={status.database.sourceOrigins} sources={status.database.sources} save={async s=>{await api('sources.save',{sources:s});await refresh();}}/></section><Subscriptions subscriptions={status.database.subscriptions??[]} refresh={refresh}/></>}
 {tab==='about'&&managerMode&&<><div className="list-heading"><div><h1>{t("关于 Framely")}</h1></div></div><SystemUpdates status={status} refresh={refresh}/><section className="settings-card"><h2>{t("用户协议与隐私声明")}</h2><div className="row"><button onClick={()=>setReviewAgreement(true)}>{t("查看协议与隐私声明")}</button></div></section></>}
 {tab==='settings'&&(!managerMode?<div className="quick-settings"><button className="setting-entry" onClick={()=>void api('host.manager.open')}><span className="setting-symbol"><Icon name="plugins" size={28}/></span><span><b>{t("管理插件")}</b><small>{t("安装、更新与管理插件源")}</small></span><span className="forward">›</span></button><section className="settings-card"><h2>{t("运行模式")}</h2><button className="setting-toggle" onClick={()=>void action(()=>api('safeMode',{enabled:!status.database.safeMode}))}><span><b>{t("安全模式")}</b><small>{t("暂停所有第三方插件")}</small></span><span className={`toggle ${status.database.safeMode?'on':''}`}/></button></section><LanguageSettings selectionOnly value={status.database.language??'auto'} packs={localePacks.current??[]} invalidFiles={languageFiles} refresh={refreshLanguages}/><button className="setting-entry quick-update-entry" onClick={()=>void action(()=>api('host.manager.open',{page:'updates'}))}><span className="setting-symbol"><Icon name="refresh" size={28}/></span><span><b>{t("检查更新")}</b></span><span className="forward">›</span></button><div className="about"><Brand/><b>Framely</b><small>{t("版本")}{status.build??status.version}</small></div></div>:<><div className="list-heading"><div><h1>{t("设置")}</h1><p>{t("运行模式与诊断。")}</p></div></div><LanguageSettings value={status.database.language??'auto'} packs={localePacks.current??[]} invalidFiles={languageFiles} refresh={refreshLanguages}/><NetworkSettings config={status.database.networkPanel??{enabled:true,port:15915}} refresh={refresh}/><ProxySettings config={status.database.proxy??{http:"",github:""}} refresh={refresh}/><section className="settings-card"><h2>{t("恢复与诊断")}</h2><div className="row"><button onClick={()=>void action(()=>api('safeMode',{enabled:!status.database.safeMode}))}>{status.database.safeMode?t("退出安全模式"):t("进入安全模式")}</button><button onClick={()=>void action(async()=>setLogs(JSON.stringify(await api('status'),null,2)))}>{t("诊断信息")}</button></div></section><section className="settings-card"><h2>{t("运行用户")}</h2><p className="sub">{t("steamos 使用 Steam 会话用户运行；root 使用系统管理员运行。安装前请确认插件来源和运行用户。")}</p></section></>)}
 {tab==='catalog'&&<Store target={catalogTarget} plugins={status.database.plugins} sources={status.database.sources} onInspect={inspect} onSources={()=>setTab('sources')} busy={busy}/>}
 </main></div>}
 {importing&&<div className="modal" role="dialog" aria-modal="true" aria-label={t("安装插件")}><button className="icon-button modal-close" aria-label={t("关闭导入")} onClick={()=>setImporting(false)}><Icon name="close"/></button><InstallInput inspect={async p=>{await inspect(p);setImporting(false);}} busy={busy}/></div>}
 {manage&&<div className="modal manage-dialog" role="dialog" aria-modal="true" aria-label={t("管理插件")}><h2>{manage.manifest.name}</h2><PluginLinks plugin={manage.manifest}/><p><PluginAuthor plugin={manage.manifest}/> · {manage.manifest.version} · {manage.manifest.backend?.runAs??manage.manifest.lifecycle?.runAs??'steamos'}</p><MemoryLimit manifest={manage.manifest}/>{status.database.plugins[manage.manifest.id]?.error&&<p className="error">{status.database.plugins[manage.manifest.id].error}</p>}<details className="plugin-relations"><summary>{t("插件依赖")}</summary><RelationsInfo plugin={manage.manifest}/></details><div className="row"><button onClick={()=>move(manage,-1)}>{t("上移")}</button><button onClick={()=>move(manage,1)}>{t("下移")}</button></div><div className="manage-grid"><button disabled={busy} onClick={()=>void action(async()=>{await changePlugin(manage,'enable');})}>{manage.enabled?t("停用"):t("启用")}</button><button disabled={busy||!manage.enabled} onClick={()=>void action(()=>api('plugin.restart',{plugin:manage.manifest.id}))}>{t("重启后端")}</button><button disabled={busy} onClick={()=>{setCatalogTarget({plugin:manage.manifest.id,source:manage.source});setManage(null);setPage(null);setTab('catalog');}}>{t("可选安装版本")}</button><button onClick={()=>void action(async()=>setLogs(await api('logs',{plugin:manage.manifest.id})))}>{t("查看日志")}</button><button className="danger" disabled={busy} onClick={()=>void action(async()=>{await changePlugin(manage,'uninstall');if(page===manage.manifest.id)setPage(null);})}>{t("卸载")}</button>{status.database.plugins[manage.manifest.id]?.error?.includes("卸载清理失败")&&<button className="danger" disabled={busy} onClick={()=>void action(async()=>{await changePlugin(manage,'uninstall',{force:true});})}>{t("强制卸载（跳过清理失败）")}</button>}</div><div className="dialog-footer"><button onClick={()=>setManage(null)}>{t("关闭")}</button></div></div>}
 {install&&<InstallReview title={installTitle} info={install.info} busy={busy} error={error} confirmed={confirmRunAs} onConfirmChange={setConfirmRunAs} onChoose={(id,url)=>void resolveChoice(id,url)} onCancel={()=>setInstall(null)} onInstall={()=>void action(async()=>{await runJob('install.start',{ticket:install.ticket,approve:true,approveRunAs:confirmRunAs},setTransfer);setInstall(null);setTransfer(null);})}/>}

 {transfer&&<Transfer job={transfer} retry={downloadRequest&&transfer.kind==='inspect'?()=>void inspect(downloadRequest):undefined} cancel={()=>void api('job.cancel',{job:transfer.id}).then(()=>setTransfer(v=>v?{...v,phase:'cancelled'}:null))} close={()=>setTransfer(null)}/>}
 {relationAction&&<div className="modal"><h2>{relationAction.title}</h2>{!!relationAction.enable.length&&<p>{t("启用：")}{relationAction.enable.map((id:string)=>status.database.plugins[id]?.manifest.name??id).join(', ')}</p>}{!!relationAction.disable.length&&<p className="banner">{t("停用：")}{relationAction.disable.map((id:string)=>status.database.plugins[id]?.manifest.name??id).join(', ')}</p>}<button disabled={busy} className="primary" onClick={()=>void action(async()=>{await api(relationAction.method,relationAction.params);setRelationAction(null);setManage(null);})}>{t("确认执行")}</button><button disabled={busy} onClick={()=>setRelationAction(null)}>{t("取消")}</button></div>}
 {logs!==null&&<div className="modal" role="dialog" aria-modal="true" aria-label={t("诊断与日志")}><h2>{t("诊断与日志")}</h2><pre>{logs||t("暂无日志")}</pre><button onClick={()=>setLogs(null)}>{t("关闭")}</button></div>}
 </div>;
}
function InstallInput({inspect,busy}:{inspect:(p:any)=>Promise<void>;busy:boolean}){const[url,setUrl]=useState(''),[http,setHttp]=useState(false),[fileError,setFileError]=useState(''),[uploadProgress,setUploadProgress]=useState<number|null>(null);const abort=useRef<AbortController|null>(null);async function upload(file:File){const controller=new AbortController();abort.current=controller;let ticket='';setFileError('');setUploadProgress(0);try{ticket=await uploadFile(file,controller.signal,setUploadProgress,{start:size=>api('upload.start',{size}),chunk:uploadChunk,abort:upload=>api('upload.abort',{upload})});setUploadProgress(null);await inspect({upload:ticket});}catch(e){if(!controller.signal.aborted)setFileError(String(e));}finally{if(ticket)await api('upload.abort',{upload:ticket}).catch(()=>{});abort.current=null;setUploadProgress(null);}}useEffect(()=>()=>abort.current?.abort(),[]);return <section><h3>{t("导入插件包")}</h3>{fileError&&<p className="error">{fileError}</p>}<input type="file" accept=".framely" disabled={busy||uploadProgress!==null} onChange={e=>{const f=e.target.files?.[0];e.target.value='';if(f)void upload(f);}}/>{uploadProgress!==null&&<p role="status">{t("正在上传…")} {uploadProgress}% <button onClick={()=>abort.current?.abort()}>{t("取消")}</button></p>}<input placeholder={t("插件包下载 URL")} value={url} onChange={e=>setUrl(e.target.value)}/><label><input type="checkbox" checked={http} onChange={e=>setHttp(e.target.checked)}/>{t("允许测试 HTTP 地址")}</label><button disabled={busy||uploadProgress!==null||!url} onClick={()=>void inspect({url,allowHttp:http})}>{t("检查下载包")}</button><small>{t("在头显里不方便选择文件时，可使用 framely install 命令导入。")}</small></section>}
class Boundary extends React.Component<React.PropsWithChildren,{error:string|null}>{state={error:null as string|null};static getDerivedStateFromError(e:Error){return {error:e.message}}render(){return this.state.error?<div className="app"><h1>{t("界面发生错误")}</h1><p>{this.state.error}</p><button onClick={()=>location.reload()}>{t("重新加载")}</button></div>:this.props.children;}}
createRoot(document.getElementById('root')!).render(<Boundary><App/></Boundary>);console.log('FRAMELY_VIEW_READY');
