import {SwitchRow} from './switch';
import {t} from './i18n';
import React,{useEffect,useState} from 'react';
import {api} from './api';
export type NetworkPanel={enabled:boolean;port:number;passwordEnabled?:boolean};
export function NetworkSettings({config,refresh}:{config:NetworkPanel;refresh:()=>Promise<void>}){
 const[enabled,setEnabled]=useState(config.enabled),[port,setPort]=useState(String(config.port)),[info,setInfo]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[passwordEnabled,setPasswordEnabled]=useState(config.passwordEnabled??false),[password,setPassword]=useState('');
 useEffect(()=>{setEnabled(config.enabled);setPort(String(config.port));setPasswordEnabled(config.passwordEnabled??false);},[config.enabled,config.port,config.passwordEnabled]);
 useEffect(()=>{let live=true;const load=()=>void api('network.status').then(value=>{if(live)setInfo(value);}).catch(e=>{if(live)setError(e.message);});load();const timer=setInterval(load,2000);return()=>{live=false;clearInterval(timer);};},[]);
 const number=Number(port),valid=/^\d+$/.test(port)&&number>=1024&&number<=65535;
 async function save(){setBusy(true);setError('');setNotice('');try{const result=await api('network.save',{enabled,port:number,passwordEnabled,...(password?{password}:{})});setPassword('');if(result.reauthenticate&&info?.localOrigin&&location.origin!==info.localOrigin&&enabled&&number===config.port){location.replace('/manager');return;}if(info?.localOrigin&&location.origin!==info.localOrigin&&(!enabled||number!==config.port||passwordEnabled!==(config.passwordEnabled??false)||!!password)){setNotice(enabled?t("已保存，请访问 http://{0}:{1} 重新连接。", {"0": location.hostname, "1": number}):t("已关闭网络管理面板，此页面连接会断开。"));}else{await refresh();setNotice(t("已保存，设置立即生效。"));}}catch(e){setError(String((e as Error).message));}finally{setBusy(false);}}
 return <section className="settings-card"><h2>{t("网络管理面板")}</h2><SwitchRow checked={enabled} label={t("允许通过 IP 和端口访问")} disabled={busy} onChange={setEnabled}/><SwitchRow checked={passwordEnabled} label={t("使用访问密码")} disabled={busy} onChange={setPasswordEnabled}/>{passwordEnabled&&<label className="network-password">{t("访问密码")}<input type="password" autoComplete="new-password" maxLength={512} value={password} placeholder={info?.passwordConfigured?t("已设置，留空则不修改"):t("设置访问密码")} onChange={e=>setPassword(e.target.value)}/></label>}<div className="row network-port"><label>{t("端口")}<input aria-label={t("网络管理端口")} type="number" min="1024" max="65535" value={port} onChange={e=>setPort(e.target.value)}/></label><button disabled={busy||!valid||(passwordEnabled&&!info?.passwordConfigured&&!password)||(enabled===config.enabled&&number===config.port&&passwordEnabled===(config.passwordEnabled??false)&&!password)} onClick={()=>void save()}>{busy?t("保存中…"):t("保存")}</button></div>{info?.listener?.enabled&&<><p className="sub">{t("让手机或电脑连接同一网络，在浏览器中打开下面的地址。")}</p>{info.ips?.length?<div className="network-addresses">{info.ips.map((ip:string)=><div key={ip}><span>{t("设备 IP：")}{ip}</span><code>http://{ip}:{info.listener.port}</code></div>)}</div>:<p className="sub">{t("未检测到设备 IP，请连接 Wi-Fi 或网线。")}</p>}<p className="sub">{config.passwordEnabled?t("已开启密码验证，访问时输入你设置的密码。"):info.passwordConfigured?t("密码验证未开启，打开上述地址即可进入管理面板。"):t("首次访问网络管理面板时，必须先设置访问密码。")}</p></>}{info?.listener?.error&&<p className="error">{info.listener.error}</p>}{info&&!info.listener?.enabled&&!info.listener?.error&&<p className="sub">{t("网络管理面板已关闭或正在启动。")}</p>}{notice&&<p role="status">{notice}</p>}{error&&<p className="error" role="alert">{error}</p>}</section>;
}
