import {t} from './i18n';
import React,{useEffect,useState} from 'react';import {api} from './api';import {Select} from './localized-select';
import {RunUserBadge} from './run-user';
import {MemoryLimit} from './memory-limit';
export function RelationsInfo({plugin}:{plugin:any}){
 const [dependencies,setDependencies]=useState<any[]>([]),[dependents,setDependents]=useState<string[]>([]),[error,setError]=useState('');
 useEffect(()=>{let live=true;async function load(){try{const [deps,users]=await Promise.all([api('plugin.dependencies',{plugin:plugin.id}),api('plugin.dependents',{plugin:plugin.id})]);if(live){setDependencies(deps);setDependents(users);setError('');}}catch(e){if(live)setError(String(e));}}void load();const timer=setInterval(()=>void load(),2000);return()=>{live=false;clearInterval(timer);};},[plugin.id]);
 return <section><h3>{t("依赖与冲突")}</h3>{error&&<p className="error">{error}</p>}{dependencies.length?dependencies.map(d=><p key={d.id}><b>{d.id}</b> · {d.required?t("必需"):t("可选")} · {typeof d.constraint==='string'?d.constraint:d.constraint.version}<br/><small>{d.available?t("可用"):!d.version?t("未安装"):!d.matches?t("版本或来源不匹配"):!d.enabled?t("已停用"):t("等待启动")}{d.version&&` · ${d.version}`}</small></p>):<p className="sub">{t("没有声明插件依赖。")}</p>}{Object.entries(plugin.conflicts??{}).map(([id,range])=><p key={id}>{t("冲突：")}{id} {String(range)}</p>)}{!!plugin.exclusiveResources?.length&&<p>{t("独占资源：")}{plugin.exclusiveResources.join('、')}</p>}{!!dependents.length&&<p>{t("依赖此插件：")}{dependents.join('、')}</p>}</section>
}
export function InstallPlan({info,choose}:{info:any;choose:(id:string,url:string)=>void}){
 const choice=info.choiceRequired;const[value,setValue]=useState('');useEffect(()=>setValue(choice?.candidates?.[0]?.url??''),[choice?.dependency]);
 if(choice)return <section><h3>{t("选择依赖来源")}</h3><p>{choice.dependency}{t("在其他来源中可用，请明确选择。")}</p><Select label={t("依赖来源")} value={value} onChange={setValue} options={choice.candidates.map((s:any)=>({value:s.url,label:`${s.name} · ${s.url}`}))}/><button disabled={!value} onClick={()=>choose(choice.dependency,value)}>{t("使用所选来源并继续检查")}</button></section>;
 if(!info.plan)return null;const plan=info.plan;const name=(id:string)=>plan.items.find((i:any)=>i.manifest.id===id)?.manifest.name??id;
 return <section className="install-plan"><h3>{t("安装计划")}</h3><div className="install-plan-items">{plan.items.map((item:any)=><article className="install-plan-item" key={item.manifest.id}><div className="install-item-heading"><b>{item.manifest.name}</b><RunUserBadge manifest={item.manifest}/></div><div className="install-item-version"><span>{item.action==='reuse'?t("复用已安装"):item.action==='update'?t("安装所选版本"):item.action==='reinstall'?t("重新安装"):t("安装")}</span><span>{item.manifest.version}</span></div><small className="install-item-source">{t("来源：")}{item.source??t("本地安装包")}{item.runAsChanged&&<span className="install-user-change">{t("运行用户变化")}</span>}</small><MemoryLimit manifest={item.manifest}/></article>)}</div>{!!plan.addSources.length&&<><h3>{t("同时添加以下插件源")}</h3>{plan.addSources.map((s:any)=><p key={s.id}>{s.name}<small className="source-url">{s.url}</small></p>)}</>}{!!plan.disable.length&&<p className="banner">{t("因冲突停用：")}{plan.disable.map(name).join('、')}</p>}{(plan.enable.length>1||plan.enable.some((id:string)=>id!==info.manifest.id))&&<p className="install-plan-effect"><span>{t("启用依赖链：")}</span>{plan.enable.map(name).join(' → ')}</p>}{!!plan.affected.filter((id:string)=>id!==info.manifest.id).length&&<p className="install-plan-effect"><span>{t("其他受影响的插件：")}</span>{plan.affected.filter((id:string)=>id!==info.manifest.id).map(name).join('、')}</p>}</section>
}
