import {t} from './i18n';
import React,{useEffect,useState} from 'react';
import {api} from './api';import {runJob,Job} from './store';
type UpdateSource={url:string};
export function SystemUpdates({status,refresh}:{status:any;refresh:()=>Promise<void>}){
 const source:UpdateSource|null=status.database.updateSource??null;
 const[error,setError]=useState(''),[busy,setBusy]=useState(false),[job,setJob]=useState<Job|null>(null),[release,setRelease]=useState<any>(null),[ready,setReady]=useState(false),[confirm,setConfirm]=useState<'apply'|'rollback'|null>(null),[installing,setInstalling]=useState(false);
 useEffect(()=>{setRelease(null);setReady(false);},[source?.url]);
 const progress=status.systemUpdate;
 async function run(method:string,params:unknown={},onDone?:(value:any)=>void){setBusy(true);setError('');try{const v=await runJob(method,params,setJob,'system.job.status');onDone?.(v.result);}catch(e){setError(String(e));}finally{setBusy(false);setJob(null);await refresh();}}
 return <section className="settings-card system-updates"><h2>{t("Framely 更新")}</h2><p>{t("当前版本：")}<b>{status.build??status.version}</b></p><p className="sub">{t("安装更新会保留插件和数据，Framely 界面会暂时关闭并重新启动。")}</p>{!source&&<p className="banner">{t("此版本尚未配置更新服务，请通过发行安装包更新。")}</p>}<div className="row"><button className="primary" disabled={busy||!source} onClick={()=>void run('system.check.start',{},v=>{setRelease(v.release);setReady(false);})}>{busy?t("处理中…"):t("检查更新")}</button><button disabled={busy||!status.previousRelease} onClick={()=>setConfirm('rollback')}>{t("回滚上一版本")}</button></div>{job&&<p className="banner">{job.kind==='system.check'?t("正在读取更新清单…"):t("正在下载并校验发行包…")}</p>}{progress?.phase==='downloading'&&<div className="download-progress"><progress max={progress.total??1} value={progress.received??0}/><p>{((progress.received??0)/1024/1024).toFixed(1)} / {((progress.total??0)/1024/1024).toFixed(1)} MiB</p></div>}{progress?.phase==='failed'&&<p className="error">{t("上次更新失败：")}{progress.error}<small>{t("诊断日志：/var/lib/framely/logs/update.log")}</small></p>}{progress?.phase==='done'&&<p className="banner">{t("上次更新操作已完成。")}</p>}{release&&<div className="release-card"><h3>{release.version}</h3><p>{release.version===(status.build??status.version)?t("当前已是此发行版本"):t("发行包大小：{0} MiB", {"0": (release.size/1024/1024).toFixed(1)})}</p><p className="prose">{release.changelog||t("发布者未提供更新说明。")}</p>{release.version!==(status.build??status.version)&&<button className="primary" disabled={busy||installing} onClick={()=>ready?setConfirm('apply'):void run('system.download.start',{},()=>setReady(true))}>{ready?t("安装已校验版本"):t("下载并校验")}</button>}</div>}{error&&<p className="error">{error}</p>}{installing&&<p className="banner">{t("正在切换版本。Framely 入口会在服务恢复后重新出现。")}</p>}{confirm&&<div className="confirm-box"><h3>{confirm==='apply'?t("安装 Framely {0}？", {"0": release.version}):t("回滚 Framely？")}</h3><p>{t("插件和数据会保留，Framely 界面会暂时关闭。SteamVR 不会被重启。")}</p><div className="row"><button className="primary" disabled={installing} onClick={()=>void(async()=>{setInstalling(true);setError('');try{await api(confirm==='apply'?'system.apply':'system.rollback',{approve:true,version:release?.version});setConfirm(null);}catch(e){setError(String(e));setInstalling(false);}})()}>{confirm==='apply'?t("确认安装"):t("确认回滚")}</button><button onClick={()=>setConfirm(null)}>{t("取消")}</button></div></div>}</section>;
}
